### ISSUE TITLE
Support navigation to overridden method/overriding methods

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#102]
plugin version: 0.63

### Description

For Java, IntelliJ supports easy navigation to the overridden superclass method and to overriding subclass methods.  Clicking the blue dot will take you to the superclass method.  It would great to provide similar support for OCaml classes.  And there are informative tooltips.

![image](https://user-images.githubusercontent.com/1253341/45919515-438def00-be4b-11e8-8c68-dc52b2b2cbe8.png)

In the superclass, clicking the blue dot lets you navigate to overriding subclass methods:

![image](https://user-images.githubusercontent.com/1253341/45919532-a54e5900-be4b-11e8-88b3-85ae1cfeb56e.png)

There's a tooltip in the superclass, too:

![image](https://user-images.githubusercontent.com/1253341/45919553-f8c0a700-be4b-11e8-9f6a-760cc514dc9b.png)

**Comment by giraud** [comment]
is it fixed in newest versions of plugin or are you describing something else ?

**Comment by jfehrle** [comment]
I'm not quite sure what I had in mind.  The project I work on uses almost no classes.  Separately, I notice the "Find Usages" option is quite slow, much slower than a global text search for the same symbol.  It seems to always scan all the source code.  But making this fast may be a lot of work.
