### ISSUE TITLE
refmt seems broken

### ISSUE THREAD

**Issue by justin808** [reasonml-editor/reasonml-idea-plugin#103]
plugin version:  0.63

Thanks for your work on this!

### Description
`refmt` seems broken. 

I'd expect the reformatted code to match running refmt at the command line. 

Is this a known issue?

**Comment by giraud** [comment]
Hi,
refmt is not broken, you should check that command line is using the same binary (node_modules/bs-platform/lib/refmt) and the same settings for columns width
