### ISSUE TITLE
Bucklescript error filepath

### ISSUE THREAD

**Issue by Coobaha** [reasonml-editor/reasonml-idea-plugin#104]
Hi!

Would be nice if bsb error output file path will lead to actual line column

```
We've found a bug for you!
./MyFile.re 97:39-67
```

`./MyFile.re` path is clickable but it scrolls to line 1 column 1

**Comment by giraud** [comment]
Can you recheck with v0.72 please ?

**Comment by giraud** [comment]
@Coobaha it's ok with 0.73 no ?

**Comment by Coobaha** [comment]
@giraud 
clicking on error path is still leading to line 1.
current format of path is `~/src/Module.re 3:22-23`
Maybe if path will have no space it might work out of the box:  `~/src/Module.re:3:22-23`

**Comment by Coobaha** [comment]
@giraud I've found a reason! It was one of the plugins that I had... Ruby plugin was a culprit. Do you have any idea how it is possible? Without ruby plugin -Editor jumps on click to correct line+column of file.

**Comment by Coobaha** [comment]
Following issue was created https://youtrack.jetbrains.com/issue/WEB-38377

**Comment by giraud** [comment]
I'm closing the issue then

**Comment by kristleifur** [comment]
(FWIW the Ruby plugin also causes this in IntelliJ version 2020.1.1 :) And the same fix works: Disabling the Ruby plugin.)
