### ISSUE TITLE
Missing/incorrect structure info for function named "string"

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#105]
plugin version: 0.63

### Description

The structure info should show `string` rather that `s` (the first parameter of `string`).  This seems specific to this exact function name; a function named `string2` works as expected.

![image](https://user-images.githubusercontent.com/1253341/46585954-72e85280-ca2c-11e8-82e3-1e37abf4535b.png)

**Comment by giraud** [comment]
Yes, I know why, but I won't fix it.
Better to not use a keyword to name your functions (even if it's possible)

**Comment by giraud** [comment]
I'm reconsidering it

**Comment by giraud** [comment]
0.67.2
