### ISSUE TITLE
Inconsistent highlighting of matching (), [] and {}

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#106]
plugin version: 0.63

### Description

I noticed that ReasonML didn't highlight the matching `[<` ... `>]` in this code (in an .ml4 file).  While I didn't expect this specialized syntax to be recognized, I did expect the default matching for `[` ... `]` would apply.

![image](https://user-images.githubusercontent.com/1253341/46586251-9f9e6900-ca30-11e8-8588-e4a107583435.png)

Experimenting a bit, I noticed some differences in the matching behavior for (), {} and []:

![image](https://user-images.githubusercontent.com/1253341/46586312-96fa6280-ca31-11e8-9122-4dd9d85412d8.png)

![image](https://user-images.githubusercontent.com/1253341/46586309-834efc00-ca31-11e8-9194-2cbf0a60453f.png)

![image](https://user-images.githubusercontent.com/1253341/46586290-45ea6e80-ca31-11e8-8274-c15ad077c089.png)

![image](https://user-images.githubusercontent.com/1253341/46586297-569ae480-ca31-11e8-81de-b9136e0eab9f.png)

These also seem a bit weird, but may have the same underlying cause:

![image](https://user-images.githubusercontent.com/1253341/46586440-5bf92e80-ca33-11e8-9b5e-4b37ea2adb3f.png)

![image](https://user-images.githubusercontent.com/1253341/46586359-40d9ef00-ca32-11e8-85db-ece2d4c119b0.png)

Also:

![image](https://user-images.githubusercontent.com/1253341/46586365-62d37180-ca32-11e8-82ec-e06ae7388ac1.png)

![image](https://user-images.githubusercontent.com/1253341/46586386-944c3d00-ca32-11e8-99b9-a427e2c62120.png)

AFAIK, OCaml lets you nest `[` ... `]` inside `[<` ... `>]`, but that may not be worth the trouble to recognize and handle that case correctly.  But it would be nice if it just treated `[<` and `>]' as if they were `[` and `]`.

**Comment by giraud** [comment]
I defined specialized tokens in the lexer (see https://github.com/reasonml-editor/reasonml-idea-plugin/blob/master/src/com/reason/lang/ReasonML.flex).
It might not be a good idea, especially [> is seen as one token and [>] is only 2 tokens, not 3.

**Comment by jfehrle** [comment]
Hmm, that doesn't seem to enable matching behavior for `[<` and `>]` in my original example (copied as text below if you want to try it).  Positioning at the last `>]` doesn't highlight the matching `[<`.  (BTW, FWIW, this was where I noticed that a function named 'string' won't show up in the Structure panel.  Existing code in the project (Coq), not something I added.)

```
let rec string loc ~comm_level bp len = parser
  | [< ''"'; esc=(parser [<''"' >] -> true | [< >] -> false); s >] ->
      if esc then string loc ~comm_level bp (store len '"') s else (loc, len)
```

**Comment by giraud** [comment]
missing pairs in https://github.com/reasonml-editor/reasonml-idea-plugin/blob/master/src/com/reason/ide/match/OclPairedBraceMatcher.java

but I'm tempted to delete these tokens.

**Comment by giraud** [comment]
removed special tokens in 0.67

**Comment by jfehrle** [comment]
Much better, thanks.
