### ISSUE TITLE
Repl tool not functioning

### ISSUE THREAD

**Issue by yunti** [reasonml-editor/reasonml-idea-plugin#107]
plugin version: 0.65

### Description

Thanks for releasing the repl tool.  Looks to have a bug which prevents me from using this as I have trouble clicking on the `Ocaml Repl` template in run configurations. (let me know if you prefer a separate issue). Then when I can click on it, it has the options of the last clicked template prior to that.  Couple of examples below:
(v 0.65 of plugin and 
PyCharm 2018.2.4 (Professional Edition)
Build #PY-182.4505.26, built on September 19, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14)

<img width="1062" alt="screenshot 2018-10-16 at 12 18 28" src="https://user-images.githubusercontent.com/1826271/47013122-06610800-d13e-11e8-99b9-0a5fa6d7051e.png">
<img width="1062" alt="screenshot 2018-10-16 at 12 18 46" src="https://user-images.githubusercontent.com/1826271/47013126-07923500-d13e-11e8-9075-3ec3b27ba5ee.png">

**Comment by giraud** [comment]
REPL needs modules. Can you / do you have configured module ? see the wiki for that.
I don't know if pycharm accepts modules

**Comment by yunti** [comment]
Hmm thanks, not sure what you mean by configured module, or which wiki you are referring to?
I have the reasonml plugin working and installed and that all works ok, just not the REPL which was recently added.

**Comment by giraud** [comment]
Sorry, REPL is only available in IDEA (community and ultimate).
I updated the config to hide it in other versions.

**Comment by yunti** [comment]
Trying to use this in Intellij ultimate now.  However get an SDK error, (even though the bucklesript compiler etc... al works correctly)

<img width="824" alt="image" src="https://user-images.githubusercontent.com/1826271/49762028-76b08380-fcc0-11e8-9570-029534863511.png">

**Comment by giraud** [comment]
@yunti you need to define a SDK before using it, see https://github.com/reasonml-editor/reasonml-idea-plugin/wiki/Configure-an-ocaml-project

**Comment by giraud** [comment]
@yunti yes, ocaml need to be installed.

**Comment by yunti** [comment]
@giraud Thanks installed via brew on macos but I'm not clear if that can be picked up by intellij properly.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/1826271/49817550-71a70f00-fd68-11e8-83d8-269a61168a1f.png">

**Comment by yunti** [comment]
Hmm still can't find a way to get this unfortunately.....

**Comment by giraud** [comment]
@yunti did you look at the link I gave you ? it doesn't seem like you are referencing the .opam directory, in the screenshot you only have symlinks to ocaml binaries.
Maybe you expect something particular that is not yet implemented ? it is a very rough implementation.

**Comment by yunti** [comment]
@giraud yes thanks I took a look at that.  Couldn't figure out at first how to get it to point to the right place.  In the end got it to work by pointing to the opam directory directly, not attempting to use the symlinks that homebrew uses on mac.  Pointed it to /usr/local/Cellar/ocaml/4.07.1
<img width="659" alt="image" src="https://user-images.githubusercontent.com/1826271/49928034-2bac9100-feb7-11e8-88b1-40b4dfa7f50d.png">

However as it's 4.07.1 it doesn't work (won't let me type) 
<img width="705" alt="image" src="https://user-images.githubusercontent.com/1826271/49928120-60204d00-feb7-11e8-8143-72cf5cfa1b9d.png">

Homebrew only let's you install the latest version so I need to figure out how best to install the older version of ocaml which matches...


Probably best in the end if we can just use the ocaml version included with reason so it's easier for people to setup (only need to install reason/ bsb platform and reason-cli) and don't also need to install ocaml and make the version match up).

Appreciate that this is just a rough implementation and that you are out here on your own making this plugin - which is amazing by the way. (Thanks for all your work on it).

**Comment by yunti** [comment]
Done thanks
