### ISSUE TITLE
reason language id in markdown preview

### ISSUE THREAD

**Issue by Coobaha** [reasonml-editor/reasonml-idea-plugin#108]
plugin version: 
0.66
### Description

Github markdown highlights reason code only with 
```
```reason
```

But inside IntelliJ markdown plugin preview highlights only with
```
```reasonml
```

**Comment by giraud** [comment]
I don't understand the relation with this plugin

**Comment by Coobaha** [comment]
I was also not sure, but it detects reasonml and injects your plugin. So I assumed that there is some identifiers table to map language id to plugin?

**Comment by giraud** [comment]
oh, nice.
yes the language id I use is ReasonML.
I think I can rename it to Reason without too much impact

**Comment by giraud** [comment]
I don't know, unfortunately, jetbrains documentation is very sparse.

**Comment by giraud** [comment]
fixed in 0.67
