### ISSUE TITLE
Function parsing is not correct

### ISSUE THREAD

**Issue by Coobaha** [reasonml-editor/reasonml-idea-plugin#113]
plugin version: 
0.67
### Description

Function body parsing was not fully fixed 

![screencast 2018-10-30 14-46-17](https://user-images.githubusercontent.com/2446638/47719073-b2ccdf00-dc52-11e8-9df8-f43a4086c9cf.gif)

```
() =>
  switch (isBuggy()) {
  | _ => "buggy"
  };
```

**Comment by giraud** [comment]
0.67.1
