### ISSUE TITLE
"end" highlighted the same way as an unmatched parenthesis

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#115]
plugin version: 0.67

### Description

When you put the cursor in or just after "end", it's highlighted the same way that an unmatched parenthesis is highlighted.  Perhaps the intention was to highlight the matching "begin"?  That would be a nice feature.  (Clicking on "begin" doesn't highlight anything, BTW.)

![image](https://user-images.githubusercontent.com/1253341/48241656-b2d48980-e38c-11e8-801b-42447488ad7f.png)

![image](https://user-images.githubusercontent.com/1253341/48241809-4b6b0980-e38d-11e8-90b0-55d241590f4a.png)

**Comment by giraud** [comment]
0.67.1

**Comment by jfehrle** [comment]
Great, thanks!

**Comment by giraud** [comment]
I added object/end in next release.
you can see all pairs here : https://github.com/reasonml-editor/reasonml-idea-plugin/blob/master/src/com/reason/ide/match/OclPairedBraceMatcher.java
If you think of other match I can add them here

**Comment by jfehrle** [comment]
It's smart enough not to get confused when there are multiple items paired with "end"?  Highlighting "struct" in "struct ... begin ... end ... end" will do the right thing?

How about adding these?
- **do ... done** (while and for)
- **let ... in**
- **try ... with** Probably means adding **match** ... **with**, too.  But may get confused by "**{** expr **with** field [**:** typexpr] [**=** expr] {**;** field [**:** typexpr] [**=** expr]} [**;**] **}**" syntax, in which the **with** is not closing anything (manual page 122).

**Comment by jfehrle** [comment]
The **let** may not work because top-level **let**s don't have to have **in**.
