### ISSUE TITLE
Structure panel: show items defined in modules

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#116]
plugin version: 0.67.1

### Description `background_subgoals` should appear as a subnode of `V82` in the structure panel.

![image](https://user-images.githubusercontent.com/1253341/48307156-eaae0f00-e4fb-11e8-850c-873e63423f7a.png)

**Comment by giraud** [comment]
0.67.2

**Comment by jfehrle** [comment]
Looks good, also the fix for #105 looks good, thanks!
