### ISSUE TITLE
Make error locations in bucklescript tool window clickable

### ISSUE THREAD

**Issue by yunti** [reasonml-editor/reasonml-idea-plugin#122]
Like run windows for other languages in Intellij they often have the error location clickable so that when clicked it goes straight to the error location.

comment in #104 suggests that previously this was clickable, so this may be a bug.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/1826271/49757170-a73df080-fcb3-11e8-8b49-550456c29d20.png">

**Comment by giraud** [comment]
Fixed in 0.72. Thanks to msebire

**Comment by yunti** [comment]
Nice already very useful
