### ISSUE TITLE
Repl freezes with Ocaml 4.07

### ISSUE THREAD

**Issue by yunti** [reasonml-editor/reasonml-idea-plugin#124]
plugin version: 
v0.68
platform: (macOS Mojave 10.14.1)
Intellij Ultimate: 2018.3.1
Ocaml 4.07.1

### Description
When trying to launch the repl through the Ocaml Repl run configuration - the Repl is unable as the user is unable to type in it. 

<img width="679" alt="image" src="https://user-images.githubusercontent.com/1826271/49929589-be026400-feba-11e8-858a-d327b2c16b9f.png">

**Comment by giraud** [comment]
Fixed in 0.94. See also https://github.com/reasonml-editor/reasonml-idea-plugin/blob/master/docs/configuring-ocaml-project.md
