### ISSUE TITLE
Function parameter info attempts to show return type

### ISSUE THREAD

**Issue by yunti** [reasonml-editor/reasonml-idea-plugin#126]
plugin version: 
V0.68

### Description
function parameter info (cmd +p) on mac tries to show return type and show the incorrect type. (At least that's what I think it's trying to show).

eg below the parameter info tries to show a polymorphic variable as the return type (where it's unit).
 (it should really just show parameter info)
<img width="817" alt="image" src="https://user-images.githubusercontent.com/1826271/49998745-f2deeb80-ff8c-11e8-9ce6-aa208db93114.png">

eg here's a python example

![](https://user-images.githubusercontent.com/1826271/45889686-fe20e180-bdb8-11e8-9c67-d3a4b7ebd302.png)

or swift

![](https://www.jetbrains.com/objc/features/img/smart-editor/parameter-info@2x.png)

**Comment by giraud** [comment]
return type removed in 0.72
