### ISSUE TITLE
Highlight for variants not working correctly 

### ISSUE THREAD

**Issue by psiservices-vtorres** [reasonml-editor/reasonml-idea-plugin#131]
plugin version: v0.69.1

### Description

After updating the plugin version to the latest one, my PyCharm stopped showing the correct highlighting for variants/union types and the swtich statements. The same is happening with Rider. I'm no sure what previous version I had installed though, but after updating the highlighting was gone.

![image](https://user-images.githubusercontent.com/44499824/50561559-c4d70680-0d03-11e9-8185-a0eadb2e28f3.png)

**Comment by yunti** [comment]
Same here,

<img width="551" alt="image" src="https://user-images.githubusercontent.com/1826271/50969847-9b726380-14d7-11e9-8254-dd2c80f80ab1.png">

with settings as 
<img width="381" alt="image" src="https://user-images.githubusercontent.com/1826271/50969863-a7f6bc00-14d7-11e9-8138-0a89b7ee1f97.png">
