### ISSUE TITLE
syntax error tooltip popup is truncated

### ISSUE THREAD

**Issue by yunti** [reasonml-editor/reasonml-idea-plugin#133]
plugin version: 
v39 beta
### Description
errors which hovered over (red unerline) appear in the tool tip as `ax error` instead of syntax error

<img width="133" alt="image" src="https://user-images.githubusercontent.com/1826271/50975712-265a5a80-14e6-11e9-8c7d-07817e362b82.png">

**Comment by giraud** [comment]
V39beta ?
Also, can you provide the console output ?

**Comment by yunti** [comment]
Whoops sorry that is haskell plugin version. It's v0.69.1

**Comment by yunti** [comment]
bucklescript console output is:
```
/Users/yunti/.config/yarn/global/node_modules/bs-platform/lib/bsb.exe -make-world
[1/2] ninja: error: rebuilding 'build.ninja': subcommand failed
Building src/Demo.mlast
File "/Users/yunti/Projects/reason/test/src/Demo.re", line 115, characters 0-21:
Error: Syntax error
File "/Users/yunti/Projects/reason/test/src/Demo.re", line 1:
Error: Error while running external preprocessor
Command line: /Users/yunti/.config/yarn/global/node_modules/bs-platform/lib/refmt.exe --print binary '/Users/yunti/Projects/reason/test/src/Demo.re' > /var/folders/9j/zvklhn0130d55731sx1zqh300000gn/T/ocamlppa5efd4
```

Interestingly the tooltip error only appears when I run the js file with node, not when I build with the bucklescript window.

**Comment by giraud** [comment]
should not happen in
