### ISSUE TITLE
Top-level declaration following "let f = function ... and" doesn't appear in the structure panel 

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#135]
plugin version: 0.69.1

### Description
"missing" should appear in the structure panel.  Appears related to having no explicit arguments for f1, i.e. `let f1 = function ... and`

![image](https://user-images.githubusercontent.com/1253341/51069973-42e1ba00-15ee-11e9-88ff-55d85dc517c7.png)

**Comment by giraud** [comment]
fixed in 0.71

**Comment by jfehrle** [comment]
That's better, thanks!
