### ISSUE TITLE
Unicode characters inside strings turn into question marks

### ISSUE THREAD

**Issue by foxbunny** [reasonml-editor/reasonml-idea-plugin#136]
plugin version: v0.70

WebStorm 2018.3.3
Build #WS-183.5153.33, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

### Description

Taking code from the example, if I type:

```reason
let world = {js|世界|js};
```

and save the file, any non-ASCII characters become `?`:

```reason
let world = {js|??|js};
```

**Comment by giraud** [comment]
fixed in 0.71, forcing UTF-8.
