### ISSUE TITLE
.ml and .mli suffixes no longer show in File Navigate (CTRL-SHIFT-N) popup

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#137]
plugin version: 0.71

### Description

The File Navigate popup used to show the file suffix for .ml and .mli files.  It no longer shows them.  This is not a useful change because:
- all other file types show their suffix
- the little icons on the left are hard to make out (pale colors don't help) and not easy to read/scan.
- you will almost always have both a .ml and .mli file with the same base name, so you'll need to distinguish the two frequently

Notice that .java files, for example, show both an icon and the .java suffix.

![image](https://user-images.githubusercontent.com/1253341/51781767-2ce5f600-20d2-11e9-969b-86547f79982c.png)

When I disable the plugin, the suffixes re-appear:

![image](https://user-images.githubusercontent.com/1253341/51781774-5b63d100-20d2-11e9-9f21-5dcc5594c7a8.png)

**Comment by giraud** [comment]
That is not intended.

**Comment by giraud** [comment]
not present anymore in 0.76

**Comment by jfehrle** [comment]
Looks better, thanks!
