### ISSUE TITLE
bug: prevent autocomplete completing on pressing enter

### ISSUE THREAD

**Issue by yunti** [reasonml-editor/reasonml-idea-plugin#138]
plugin version: v0.69.1

### Description
When using the editor and eg typing a variable name and then pressing enter if that happens to match anything in the autocomplete dialogue then the plugin will use that. (eg typing the variable `y` and pressing enter keeps on outputting `type` ). Generally for other languages in Intellij they work by using the autocomplete if `Tab` is pressed and ignoring it if enter it pressed.

This makes it very hard currently to work with any reasonably short variable names as the autocomplete keeps trying to interfere and change them.

**Comment by giraud** [comment]
I have the same behavior in intellij idea when I use java.
it's default behavior. you can change it in settings if you uncheck 'Auto-display code completion' in Editor|General|Code Completion

**Comment by yunti** [comment]
perfect , thanks for explaining.
