### ISSUE TITLE
Feature: continuous bucklescript compilation

### ISSUE THREAD

**Issue by yunti** [reasonml-editor/reasonml-idea-plugin#139]
plugin version: v0.69.1

### Description
(this may already be a feature - if it I I just couldn't find it)

Updated----
Add an option to the bucklescript tool window to build and watch (ie `bsb -make-world -w`)

So that eg we can view reason and js files.side by side and quickly see the updated js output whilst writing reason code?

**Comment by yunti** [comment]
This can be done by using the `bs -make-world -w` command (where the -w flag uses a watcher for file changes to continously rebuild.  This is a default script in `package.json` in the bsb theme basic reason.  So to use this right click on package.json to launch the npm tool window and then use the start script.

However intellij seems to have an issue with auto refreshing an updated file. (here a js file which has been compiled by bucklescript). After saving changes to a reason file, which are then auto compiled to a new js file I can't get the new js file to appear in intellij until I show and hide the terminal window (there may be other ways but that was the most consistent for me) - viewing another file and going back to the js file didn't seem to refresh the file reliably.  

Would be interested to hear if anyone has the same issue (and whether this in an intellij bug rather than reasonml plugin bug)

**Comment by giraud** [comment]
what I do is map the synchronize action to 'alt + s', then I use that keys instead of 'ctrl + s' to save a file: it the same but with generated files automatically refreshed

**Comment by yunti** [comment]
Hmm using the npm tool window tool window to continously build and watch for file changes can't doesn't handle the coloured output from the bsb compiler.  Perhaps it would be best to add a build and watch option/icon to the bucklescript window.

**Comment by yunti** [comment]
Cross comments.. :). Thanks that's a great suggest to synchronize, I'll try that.

**Comment by giraud** [comment]
there is no watch because bsb is run each time a source file is saved (no deamon process). but when the file is saved depends on your idea settings.

**Comment by giraud** [comment]
I'm sorry I don't understand the watch option: files are already watched by idea itself. I can't launch bsb until the buffered editors are flushed to disk.
