### ISSUE TITLE
Environment variables for bsb

### ISSUE THREAD

**Issue by Coobaha** [reasonml-editor/reasonml-idea-plugin#140]
plugin version: 
0.71
### Description

To use genType, I need to provide env variable to bsb
https://github.com/BuckleScript/bucklescript/blob/43e66af869c0cd4b0aa74d3e0add0e2a3b17b1be/jscomp/bsb/bsb_parse_sources.ml#L244

Will be excellent if env variables can be configured per project. For now, I am running separate bsb process

**Comment by giraud** [comment]
a small setup example so I can reproduce it ?

**Comment by Coobaha** [comment]
Bsb doesn’t need env variables anymore, let’s close this
