### ISSUE TITLE
Add navigation from interface to implementation in module

### ISSUE THREAD

**Issue by yunti** [reasonml-editor/reasonml-idea-plugin#141]
plugin version: v.69.1

### Description
currently it doesn't seem possible to navigate from the definition in an interface .rei file to it's implementation (if that's the correct term) in a module (.re).

eg to pick a simple example to illustrate,  to go from the reprocessing Constants.rei declaration `let pi: float` to it's definition in Constants.re `let pi = 4.0 *. atan(1.0);`

**Comment by yunti** [comment]
this looks to be a very similar request to #81 except for reason files rather than ocaml

**Comment by giraud** [comment]
That should work with latest plugin version
