### ISSUE TITLE
Go to module let bindings broken in third party modules

### ISSUE THREAD

**Issue by yunti** [reasonml-editor/reasonml-idea-plugin#143]
plugin version: 0.71

### Description
Goto a module binding appears broken (this looked different to the other goto issue bugs).
Eg in the below I can navigate to the Draw module but not Draw.background.

or to `Constants` but not `Constants.black`

<img width="312" alt="image" src="https://user-images.githubusercontent.com/1826271/52242220-f5472d00-28cd-11e9-8616-71822e4801e7.png">

Related, It also means that completion for module bindings don't work
<img width="263" alt="image" src="https://user-images.githubusercontent.com/1826271/52242953-0ee97400-28d0-11e9-9c21-0cf84f9c8043.png">
Here is should have found Draw.rect

_i've found that this it works for inbuilt modules eg `Array.make_matrix()` but not for third party modules

**Comment by giraud** [comment]
is your third party lib using bucklescript namespacing (namespace: true in bsconfig) ? if yes, it doesn't work

**Comment by yunti** [comment]
No don't think that's the issue as namespacing is false by default and it's not used in reprocessing. 
https://github.com/Schmavery/reprocessing/blob/master/bsconfig.json

**Comment by giraud** [comment]
I'm reworking the finder mechanism (I'm trying to use custom idea indexes). I hope to get better results / manage namespaces. But it takes time.

**Comment by yunti** [comment]
No problem, really appreciate the work. Frustrating that I can't jump in as I don't know java (must dedicate some time to that :)

**Comment by yunti** [comment]
Interestingly I had the same issue when trying vscode, so it may not be a plugin issue.  I'm not sure what might be the common cause though between this and reason-language-server as this plugin doesn't appear to use merlin.

**Comment by giraud** [comment]
I think it's an unfortunate coincidence. This is clearly a plugin problem

**Comment by yunti** [comment]
Ah ok, thought it was worth mentioning in case it was a shared issue. :)

**Comment by giraud** [comment]
@yunti you could try this beta: https://bintray.com/giraud/idea-plugin/download_file?file_path=reasonml-plugin-idea-0.73-beta01.zip . it's not done yet but it should already be better than 0.72.

**Comment by yunti** [comment]
@giraud.  Thanks but now I think I've messed up intellij somehow.
<img width="474" alt="image" src="https://user-images.githubusercontent.com/1826271/52785419-d6743380-304f-11e9-9486-0e395c7f8719.png">

**Comment by giraud** [comment]
you need to install the zip itself

**Comment by yunti** [comment]
@giraud Thanks.  (macOs autounzips so that messed things up a bit). 
I can't yet go to declarations of modules or module functions (third party or stlib). 

eg
<img width="414" alt="image" src="https://user-images.githubusercontent.com/1826271/52802474-ec95ea00-3077-11e9-85b5-09c016327f6c.png">
and also a module's function eg `List.length`
<img width="662" alt="image" src="https://user-images.githubusercontent.com/1826271/52802620-38489380-3078-11e9-9e9f-293ce28c2e0a.png">

(Note although it says usages I am doing the shortcut for declaration)
<img width="662" alt="image" src="https://user-images.githubusercontent.com/1826271/52802579-2c5cd180-3078-11e9-9d69-c998f81f69fd.png">

However I can go to a third party module declaration here Env in reprocessing (but a module's function/binding won't work).  Ie `Env` is ok but not eg  `Env.keyPressed()`

<img width="216" alt="image" src="https://user-images.githubusercontent.com/1826271/52802896-bd33ad00-3078-11e9-96f3-5d94a477842e.png">

There also seems to now be a gutter link between the signature (rei) and the actual function. 
and this works both ways, which is brilliant.  (Don't think this was there before.)
<img width="385" alt="image" src="https://user-images.githubusercontent.com/1826271/52803142-582c8700-3079-11e9-91c5-0b27cd804c82.png">

**Comment by yunti** [comment]
This test project uses bsb-native rather than bsb-platform - so I had can't find bsb-platform error popup. (it's based off https://github.com/bsansouci/reprocessing-example/blob/master/package.json)I I did try to link in the plugin settings to the yarn globally installed version but wasn't clear if that worked.
 Instead Installing it `yarn add -D bsb-platform` means that I can now goto the declarations for stlib modules and functions.  
However there are some issues, it seems I can't goto a declaration if it is used twice in the module. eg  the first `Array.fold_left()` doesn't work but the second does.
<img width="331" alt="image" src="https://user-images.githubusercontent.com/1826271/52806296-81044a80-3080-11e9-9461-fb19f501da10.png">

**Comment by giraud** [comment]
oh you're working with native that's different. 

With bs-platform, the stdlib is automatically indexed, not with native. I'm working on a setting for the native side but it's very rough at the moment, and things are very fuzzy.

For native, you first need to setup a SDK and add the sources, like explained here https://github.com/reasonml-editor/reasonml-idea-plugin/wiki/Configure-an-ocaml-project .

Then I'm trying to implement an ocaml module to specify the different sources.
You need to add / replace the module with an ocaml one:
![image](https://user-images.githubusercontent.com/239612/52821093-21249880-30ae-11e9-8966-5374f97c443f.png)
![image](https://user-images.githubusercontent.com/239612/52821184-60eb8000-30ae-11e9-93ba-957dc0e5481d.png)

and then you need to set the source directories
![image](https://user-images.githubusercontent.com/239612/52821282-a3ad5800-30ae-11e9-80ca-b27588bee40d.png)

That's the idea for the native workflow. As I said it's very rough right now (I'm not even sure it persist the config corretly), but it's to give you a view of how I imagine things. It mimics how it's done in java, and I think it can integrate nicely in idea (with more automation, for ex, .merlin could be synced to setup the sources).

**Comment by yunti** [comment]
Thanks I'll have a look at the setup you mentioned. Thanks for detailing it.
I hadn't realised that any native work should be setup as per an ocaml project - I just thought that was for ocaml files.  

(Also It looks like bsb-native may be merged into bucklescript  https://github.com/BuckleScript/bucklescript/pull/3353
so that may help make things easier with this type of project). 
However that won't likely won't help native apps that use eg esy. 

Thanks again.

**Comment by giraud** [comment]
what I detailled is more an idea of a workflow :) it might not work !
native is more problematic, there are so many possible options. I'll focus on dune exclusively.

**Comment by giraud** [comment]
reason is ocaml 😉 😄

**Comment by yunti** [comment]
True.... ;)

**Comment by yunti** [comment]
Hmm not sure how to go about setting up ocaml support for eg bsb-native. I can't see an opam folder as per the wiki. Should it point to the /ocaml folder in bsb-native? https://github.com/bsansouci/bsb-native/tree/master/vendor/ocaml. 
What files is the plugin looking for?

**Comment by giraud** [comment]
not much today: just a folder with the version number in it 😄 . It's used mainly to get a version number and associate it with sources (in the module panel).

That's why I need the help of ocamler/native people, to have feedback to understand what would be the most natural/comprehensive workflow when doing native (and that would still be compatible with how things are structured in idea).

I have a small ocaml native project but I know too much of java to be representative. I'm too accustomed to how things work in the java world.

**Comment by yunti** [comment]
Probably a good thing to ask in discord. I'm unfortunately too inexperienced yet to give anything more than hearsay rather than decent advice. 

I suppose it's probably a question around, what specific files/binaries does the plugin need access to? And where are those normally located depending on install method for the ocaml binary (which will likely vary depending on OS).

**Comment by bsansouci** [comment]
Heyy, so for bsb-native I tried to do it as much like bs-platform as I could. For example, the native stdlib is located at `node_modules/bsb-native/lib/ocaml` (whereas as the JS one is at `node_modules/bsb-native/lib` with the built artifacts `.js` files are at `node_modules/bsb-native/lib/js`)
It also generates a `.merlin` file with the correct paths to everything which should help.

Anything else you'd need to know the path to?

**Comment by giraud** [comment]
Im on holidays for a week, sorry !

**Comment by giraud** [comment]
@bsansouci unfortunately, bsb-native doesn't work with the plugin, because it's a hybrid conf.
It has a bsconfig.json and when the plugin detects the presence of that file, it switch to the bucklescript mode, and it has some hard-coded info to make it work and that doesn't match with bsb-native.

**Comment by giraud** [comment]
@bsansouci forgot my last comment, you can have completion and navigation in native bsb.
I just tried with v0.73 and your https://github.com/bsansouci/reprocessing-example project.

What is needed is to configure the project structure like any native project.

you need an ocaml SDK with the sources attached to it (mandatory for completion and navigation):
![sdk](https://user-images.githubusercontent.com/239612/54270549-ecf2a980-457f-11e9-9766-becd67b76eb9.png)

then you need to use it in your project:
![project](https://user-images.githubusercontent.com/239612/54270569-f54ae480-457f-11e9-88c1-c589a2aa8da7.png)

and, it shouldn't be needed, but you can also replace your module with an ocaml one:
![module](https://user-images.githubusercontent.com/239612/54270593-085db480-4580-11e9-9b81-066ec97b9c26.png)
