### ISSUE TITLE
Compiler warnings sometimes not highlighted in editor

### ISSUE THREAD

**Issue by yunti** [reasonml-editor/reasonml-idea-plugin#144]
plugin version: 
v0.72
### Description
Sometimes compiler error aren't shown in the editor,
eg here yOffset and n aren't highlighted
<img width="679" alt="image" src="https://user-images.githubusercontent.com/1826271/52348122-706a2980-2a1b-11e9-81d1-225fc4c8480d.png">

Here the error is highlighted not at the error location (ie line 9 chars 27-28) but several lines below)

<img width="551" alt="image" src="https://user-images.githubusercontent.com/1826271/52349593-cf7d6d80-2a1e-11e9-811a-6d4ac5353f39.png">

<img width="611" alt="image" src="https://user-images.githubusercontent.com/1826271/52349650-e9b74b80-2a1e-11e9-9c17-0a828c9c73d4.png">

However in this example it works as standard..

<img width="436" alt="image" src="https://user-images.githubusercontent.com/1826271/52348143-8546bd00-2a1b-11e9-9445-288d4a54a386.png">

<img width="304" alt="image" src="https://user-images.githubusercontent.com/1826271/52348160-8d9ef800-2a1b-11e9-8894-e931b88b3f75.png">

**Comment by giraud** [comment]
Changed highlighting process in 0.96, it should fix it. If not, reopen the issue.
