### ISSUE TITLE
Reformat on Save toggle doesn't always work

### ISSUE THREAD

**Issue by pm-mck** [reasonml-editor/reasonml-idea-plugin#148]
plugin version: v0.72

### Description

Even with the Reformat on save control disabled under _Languages & Frameworks > Reason_, while working on an OCaml-only project (no .re or .rei files), the plugin appears to infrequently and randomly apply `refmt` to the .ml file I'm working with on save.

Unfortunately, I have not found a pattern or a way to force it to happen.

I think a good enhancement would be to only Reformat on save .re and .rei files and exclude all others, since the Reformat on save function is a welcome enhancement for ReasonML source.

**Comment by giraud** [comment]
If it happens regularly, you can do something for me: first add `ReasonML.refmt` to the debug log : menu `Help` | `Debug log settings`.
When an unwanted reformat happens, send the logs to me. You can find where the logs are produced with menu `Help` | `Show log in explorer`

**Comment by pm-mck** [comment]
An update: I did just have this happen to an ml file I had in a shared Reason/OCaml codebase.

Attached the logs from when it happened.
[refmt log.txt](https://github.com/reasonml-editor/reasonml-idea-plugin/files/2948057/refmt.log.txt)

The file queue.ml got rearranged by refmt. I shut off the refmt on save in that project and it behaved as expected.

**Comment by giraud** [comment]
Hi,
I'm not sure to understand your problem.
you say that reformat is run on save even when the setting is disabled, but it doesn't seem to be the case by looking at the logs, and in your last message.
I don't know what you expect for this issue.

**Comment by pm-mck** [comment]
Well, there's two issues:

1. It's applying refmt on ml/mli files, and it does it randomly. I'm not sure this should happen for ml/mli files, even with reformat on save is enabled.

2. I had this happen when I had it disabled before, but maybe a restart of the IDE or some other event caused it to take, I haven't had it happen again, so I think this is just a weird situation I had.

I added the logs in case they would be helpful.

**Comment by giraud** [comment]
In 0.74, ml and mli files are no more formated on save.
for random event, I have no solution

**Comment by pm-mck** [comment]
Thanks for the update!
