### ISSUE TITLE
ReasonML confused by .mly (yacc) files; structure panel shows most of the grammar on one very long line

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#149]
plugin version: 0.72

### Description

When examining .mly files, which are yacc input files, the structure panel shows most of the grammar on a single extremely long line.  That's not helpful.

It would be nice if the structure panel listed non-terminals, but I can understand if only you want to handle the more usual OCaml file types.  Second choice would be to show nothing in the structure panel, or perhaps to show the OCaml functions defined.

![image](https://user-images.githubusercontent.com/1253341/53852175-ea87c280-3f75-11e9-8486-c30aa035dac1.png)

The file is available at https://github.com/coq/coq/blob/master/coqpp/coqpp_parse.mly

**Comment by giraud** [comment]
The good news is that I now know how to mix grammars at the lexer level.
It becomes wayyyyy easier to do things like that.
a preview:
![image](https://user-images.githubusercontent.com/239612/53897800-3484ad00-4037-11e9-834b-8e55ee687101.png)

**Comment by jfehrle** [comment]
That's great!

**Comment by giraud** [comment]
Fixed in 0.73

**Comment by jfehrle** [comment]
Looks much better!

Two further details:

1. Probably not useful to show just the keyword `%token` multiple times in the structure panel.  Maybe show each defined token instead (e.g. CODE, COMMENT, etc.)?

![image](https://user-images.githubusercontent.com/1253341/54242208-01cc3000-44e1-11e9-87e8-6140336625ab.png)

2. The nonterminals always appear in the order they are defined in the file even when alphabetical order is selected.

![image](https://user-images.githubusercontent.com/1253341/54242324-67b8b780-44e1-11e9-910e-e39c218f641e.png)
