### ISSUE TITLE
Consider using the language server

### ISSUE THREAD

**Issue by freebroccolo** [reasonml-editor/reasonml-idea-plugin#15]
I was just wondering if you have considered using the [OCaml language server](https://github.com/freebroccolo/ocaml-language-server) like some of the other plugins are doing. There is an [LSP plugin](https://github.com/gtache/intellij-lsp) that would facilitate communication with the server. cc @chenglou

**Comment by giraud** [comment]
Sure, it is something I will look at in the future, but right now it doesn't work natively on windows, so it's not an option for me.

**Comment by freebroccolo** [comment]
You mean the language server doesn't work natively on Windows? There's nothing in the language server which is inherently incompatible with windows. I thought the problem was always that building the OCaml tooling and merlin itself natively for windows.

In any case, WSL support for the language server is currently being worked on and will probably be available sometime in the next week or so. It mostly works now but there are a few other issues (unrelated) I'd like to resolve before enabling the functionality in release.

**Comment by giraud** [comment]
I might be totally wrong, didn't look much at it :) But I have the understanding that LSP can't work without all the tooling, and as you said, the tools are only supported through WSL. 
I will look at it again in few weeks then.

**Comment by freebroccolo** [comment]
The server is currently written in typescript so it will run wherever node works. The reason for the WSL support is mostly because that seems to be the easiest way for people to install the OCaml tooling on windows.

I guess what I don't understand is how your plugin gets around this issue of still needing merlin, etc. You still have to have merlin installed on windows somehow, right? How do you have that installed?

Just to be clear, if you are able to have all of the tooling installed natively somehow, in principle there is no reason why the language server wouldn't work with that. There might need to be a couple minor bug fixes required because I've never tried to run it that way but it should work.

**Comment by giraud** [comment]
"I guess what I don't understand is how your plugin gets around this issue of still needing merlin, etc. " 
it doesn't. you can't have completion, I just rely on Bsb to get the errors and annotate the source (like the reason LSP implementation I imagine). 

I think that we say the same thing. 

The only difference is that (with the plugin), I have nothing to install to just get bsb compilation and error notification. When merlin is natively available on windows, LSP might be a better choice.

**Comment by giraud** [comment]
My goal is different. My goal is to introduce reason with the minimum impact on my co workers. They use windows and intellij idea, and if I have to talk about WSL, there is no chance to introduce reason.

**Comment by freebroccolo** [comment]
I understand :)

Currently the language server does require the presence of `ocamlmerlin` on initialization but this will probably removed in the near future too because it is not strictly necessarily to have merlin available to use it. Since the last several versions it is possible to get the diagnostics through `bsb` instead. I suppose once that happens it may be more suitable for what you have in mind.

**Comment by chenglou** [comment]
cc @bobzhang who might vendor merlin in bs-platform and have it work on windows

**Comment by giraud** [comment]
I now have access to all cmt info, and since I have a quite stable and easy to use plugin, I'll keep it like that and not use LSP. I think there is space for other plugin that could use LSP
