### ISSUE TITLE
Structure panel should omit "let () = ..." items and should include "let (a,b) = ..." items

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#153]
plugin version: 0.73

1. Top level lets in the form `let () = ...` **should not** appear in the structure panel since they don't have name.  For example:

![image](https://user-images.githubusercontent.com/1253341/54859643-eb865700-4ccc-11e9-8f92-aabf685b38a8.png)

2. Top level lets in the form `let (a, b) = ...` **should** appear in the structure panel with names `a` and `b`.  For example:

![image](https://user-images.githubusercontent.com/1253341/54859647-fa6d0980-4ccc-11e9-8742-1753a4fdde47.png)

Code for the examples is here: https://github.com/coq/coq/blob/master/vernac/vernacentries.ml

**Comment by giraud** [comment]
Fixed in 0.74

**Comment by jfehrle** [comment]
Looks better on # 1, thanks.

I would have split `let (f_interp_redexp, interp_redexp_hook)` into 2 separate entries in the structure panel.  Both are top-level variables.  They just happen to both be defined in the same let.  If I'm looking for `f_interp_redexp` when the structure panel is alphabetized I'd expect to find it between `focus_cmd_cond` and `get_current_context_of_args`

![image](https://user-images.githubusercontent.com/1253341/54908635-99e4f480-4ea5-11e9-874e-8e728909fa0f.png)

Also, a different issue: I'd expect the `open`s to be alphabetized when the panel has alphabetic order selected.  And probably I'd intermix them with other symbols.

![image](https://user-images.githubusercontent.com/1253341/54909048-838b6880-4ea6-11e9-9975-0d98f55b64ec.png)

**Comment by giraud** [comment]
Fixed in 0.75

**Comment by jfehrle** [comment]
Looks good!
