### ISSUE TITLE
Disable end of line after reformat

### ISSUE THREAD

**Issue by cem2ran** [reasonml-editor/reasonml-idea-plugin#154]
plugin version: (Think this always has existed, I'm on latest)

### Description

It seems that a new line is always added to a file when reformat on save is enabled. I'm not sure if this is due to editor configuration or if it can be added as a configuration to refmt.

**Comment by giraud** [comment]
Hi, this is a refmt rule, this plugin does nothing wrt formatting.

**Comment by cem2ran** [comment]
Apologies for reopening this, but where would I set this refmt rule, when used in conjunction with this plugin? When using the vscode plugin I do not see this behavior.

**Comment by cem2ran** [comment]
@giraud ?

**Comment by giraud** [comment]
yeah might be from the plugin, need to investigate

**Comment by giraud** [comment]
fixed in 0.75
