### ISSUE TITLE
Function not shown in the structure panel with "let ... and" and optional parameter

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#159]
plugin version: 0.74

### Description

1. `maybe_unwrap` and `expand_rule` should be shown in the structure panel
2. Probably `get_prods` and `maybe_unwrap` should be shown as hideable subnodes of `maybe_add_nt` since they are available on in the scope of `maybe_unwrap`

Commenting out various functions changes which functions are missing in the structure panel.  I couldn't infer what might be happening.

![image](https://user-images.githubusercontent.com/1253341/55301777-1c643b80-53f3-11e9-9152-3aa9e9aec727.png)

```
let rec maybe_add_nt edited_nt name sym =
  let maybe_unwrap ?(multi=false) = (* need the optional
     parm to see the error, commenting out
    makes get_prods disappear and expand_rule appear *)
    Printf.printf ""
  in
  let get_prods nt =  (* removing this makes maybe_unwrap
    disappear from the structure panel *)
    Printf.printf ""
  in
  Printf.printf ""

and expand_rule b  =
  Printf.printf ""
```

**Comment by giraud** [comment]
I don't know, I'm not a fan of showing local functions in the structure view.

**Comment by jfehrle** [comment]
`expand_rule` is a top level function, so it should definitely appear in the structure panel.

I am seeing some local functions and variables appear in the structure panel.  I assumed that was intentional.  Some examples below.  Sometimes local are nice to see.  IIRC the structure panel used to have more options (e.g. for Java); showing local functions could be an option.  Or not.

This shows local variables.  Removing the `?(plist=false)` makes them disappear:

![image](https://user-images.githubusercontent.com/1253341/55648549-75d2be80-5795-11e9-9146-92b6a597c323.png)

```
let prod_to_str ?(plist=false) prod =
  let p = ref prod in
  let res = ref [] in
  while !p <> [] do
    let need_semi = 0 in
  String.concat "" (List.rev !res)
```

Another example. Removing the `?(multi=false)` on the second line makes all the non-local symbols go away.:

![image](https://user-images.githubusercontent.com/1253341/55649303-85530700-5797-11e9-8413-faab9d2e7448.png)

```
let rec maybe_add_nt edited_nt name sym =
  let maybe_unwrap ?(multi=false) sym =
    Printf.printf ""
  in
  let get_prods nt =
    let unw sym = List.hd (maybe_unwrap sym) in
    Printf.printf ""
  in
  let find_name nt =
    let nt' = ref "" in
    let i = ref 1 in
    let is_new = ref true in
    while !nt' = "" do
      let trial_name = if !i = 1 then nt else nt ^ (string_of_int !i) in
      try
        if NTMap.find trial_name !nt_map = get_prods trial_name then begin
          nt' := trial_name;
          is_new := false
        end else i := !i + 1
      with Not_found -> nt' := trial_name
    done;
    !nt', !is_new
  in
  let insert_nt new_nt =
    List.concat (List.map (fun nt ->
      if nt = edited_nt then [nt; new_nt] else [nt])
    !nt_order)
  in
  let nt', is_new = find_name nt in
  if is_new then begin
    let prods = (get_prods nt') in
    nt_order := insert_nt nt';
    nt_map := NTMap.add nt' prods !nt_map;
    expand_rule (nt', prods)
  end;
  nt', is_new

(* expand LIST*, OPT and add "empty" *)
(* todo: doesn't handle recursive expansions well, such as syntax_modifier_opt *)
and expand_rule b  =
  let nt_regex = Str.regexp "^[a-zA-Z_][a-zA-Z0-9_\\.]*$" in
  let (edited_nt, rule) = b in
  let insert_point = ref edited_nt in
  let good_name name = if Str.string_match nt_regex name 0 then name else "" in
  let map_name s =
    let s = match s with
    | _ -> s
    in
    good_name s
  in
  let rec get_name sym =
    Printf.printf ""
  in
  let rec expand prod0 =
    Printf.printf ""
  in
  let rule' = List.map expand rule in
  nt_map := NTMap.add edited_nt rule' !nt_map
```
Also: nt' should be tagged as a variable, not as a function.  edited_nt and rule should be separate entries:

![image](https://user-images.githubusercontent.com/1253341/55649585-3194ed80-5798-11e9-925e-fd3bfe726283.png)

**Comment by giraud** [comment]
0.75

**Comment by jfehrle** [comment]
Mostly fixed, but still not entirely right:
> nt' should be tagged as a variable

`is_new` should be shown in the structure panel.

With an even simpler example:

![image](https://user-images.githubusercontent.com/1253341/55993609-63102c00-5c64-11e9-8dee-67c5ce1bae51.png)

```
let nt', is_new = (1,2)
```

**Comment by giraud** [comment]
This ils a différent issue
