### ISSUE TITLE
Error Reporting for OCaml Files

### ISSUE THREAD

**Issue by JohnPucciarelli** [reasonml-editor/reasonml-idea-plugin#169]
Plugin Version: 0.76.2

### Description
Does this plugin support error reporting when used with OCaml files? I would like to use this plugin for pure OCaml and am not intending on having my code transpiled to JavaScript (no BuckleScript configured).

More specifically, I have an Ocaml file with errors being reported by merlin in vim, but I don't see any errors when opening the same file in IDEA. It's possible my project is misconfigured.

Apologies if this is addressed elsewhere. Appreciate your work on this plugin.

**Comment by giraud** [comment]
0.94 has a better integration with Dune. it should report compilation errors (on save).
![image](https://user-images.githubusercontent.com/239612/97963936-37114a00-1db8-11eb-89c7-896a0475634e.png)
