### ISSUE TITLE
A feature wish list

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#17]
Generally I'd like functionality similar to what's available for Java files.

**Understanding Code**
- Control click to jump to symbol definition (in current file or another file)
- Show definitions in the structure panel (tree of modules and lets)

**Editing**
- Detect/highlight basic syntax errors in real time
- Autocompletion (CTRL-space) suggests existing symbols that match the prefix
- Autoindent
- Need a way to see the type of a definition I the editor (e.g. a tooltip)

**Build/Debu**
- Build should invoke the compiler, display error messages in build window, let you jump to them, marked in red on the scroll bar
- Debug support would be great, e.g. for ocamldebug, even though its capabilities are a bit limited (e.g. backtrace doesn't show definition names, only line/character numbers)

The syntax coloring is helpful!

**Comment by giraud** [comment]
FYI: this plugin uses Bucklescript for the more advanced feature: syntax errors highlighting in real time and type definition annotation.
It is mandatory to install bucklescript if you want these.
