### ISSUE TITLE
Functions in struct in "module : sig ... end = struct ... end" not shown in Structure panel

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#170]
plugin version: 0.76.2

### Description

1. The structure panel shows the 4 methods listed in the signature for `Backtrack` but the other functions defined in the `struct` such as `fold_until` don't appear anywhere in the Structure panel.  Seems like they should be shown somewhere.

![image](https://user-images.githubusercontent.com/1253341/56854511-a3221080-68ec-11e9-8855-ed2c3c06dcf3.png)

2. Double clicking on any of the `Backtrack` methods takes you to the signature rather than the function body.  Probably would be more helpful to jump to the function body.

The code is in https://github.com/coq/coq/blob/master/stm/stm.ml

**Comment by giraud** [comment]
in master, impl is shown if there is both signature+body:
![impl](https://user-images.githubusercontent.com/239612/63535167-1d684780-c511-11e9-8b20-bc429350f061.png)
It removes the need for 2. , you can click on signature/body method

**Comment by jfehrle** [comment]
Looks good!  Maybe put "Implementation" in parentheses so it can't be mistaken for the name of a submodule.  The icon suggests that it's a module, but I don't have a good suggestion on how to do it better.

I suppose you'll release this soon?

**Comment by giraud** [comment]
Yes, I'm planning a release soon.

many options are possible:
a
![impl_a](https://user-images.githubusercontent.com/239612/63642797-34e83180-c6c5-11e9-9c5d-ed79f6d4f318.png)

b
![impl_b](https://user-images.githubusercontent.com/239612/63642799-39ace580-c6c5-11e9-821d-f2db80c19768.png)

c
![impl_c](https://user-images.githubusercontent.com/239612/63642802-3ca7d600-c6c5-11e9-9666-f67e7263024d.png)

d
![impl_d](https://user-images.githubusercontent.com/239612/63642803-403b5d00-c6c5-11e9-8afe-34579f3d46f4.png)

e
![impl_e](https://user-images.githubusercontent.com/239612/63642806-43cee400-c6c5-11e9-9ced-d5a44532182a.png)

**Comment by jfehrle** [comment]
"Backtrack (implementation)" is too long, so I'd eliminate e.

I would omit the icon next to the implementation label because it's not a module, so I'd eliminate a and d.  In c, `Backtrack.impl` might be taken as related to a submodule `impl` at first glance.  I think I'd go for b, but maybe use just `(impl)` as the label.

A couple other thoughts:
- It would be nice if the items under "implementation" lined up with those under the module name since they're really at the same level.  But the tree control probably doesn't support this.
- I tend to think of the implementations as being public (visible outside) or private (not visible), akin to Java.  Might be nice to indicate this somehow if it's easy.
- The V icon is used both for values (non function let statement) and entries (`val ...`) in the module signature.  I tend to think of the `val`s as another form of type info.  Perhaps they should be shown with the T icon?

![image](https://user-images.githubusercontent.com/1253341/63653918-2c751280-c728-11e9-84ec-a1001ede49b9.png)

**Comment by giraud** [comment]
the (impl) is present in 0.79.

**Comment by jfehrle** [comment]
Looks very good, thanks!
