### ISSUE TITLE
Improve default colors

### ISSUE THREAD

**Issue by nirvdrum** [reasonml-editor/reasonml-idea-plugin#182]
plugin version: 0.7.9

I've been using the Darcula theme with the JetBrains family of IDEs for a while now and never really had a problem. However, I noticed with ReasonML files, there was no real color differentiation for certain facets of the language.

I tried multiple themes and couldn't match what you have in the README. Both the default and Darcula themes were particularly problematic. The Blackboard theme looks like a nice compromise and I may just go with that for the time being.

Module names, variants, and attributes all look to have the same font color. Likewise, the built-in types such as `int` and `bool` do not receive any differentiating color.

![reasonml-darcula](https://user-images.githubusercontent.com/12584/64059787-1684a900-cb91-11e9-954b-1ae6133ed1bc.png)

I realize picking colors for every scheme is a large undertaking and may not be worth it. I think the default theme and Darcula perhaps merit special treatement, however, since JetBrains makes choosing between them part of the IDE init process.

**Comment by nirvdrum** [comment]
As a follow-up, I'm not entirely sure why Option is colored different from Variant. Should those just be collapsed into a single color entry?

**Comment by nirvdrum** [comment]
Looking into this more, there's no differentiation between lowercase identifiers at all, as far as I can tell. I think further separating these into types, fields, bindings, and so on is necessary to get more useful syntax highlighting. I suspect it would also help with "find usages" and clicking through to values & types.

**Comment by giraud** [comment]
Hi,

- the settings I use can be found in https://github.com/giraud/reason-dark-theme-jetbrains.
I don't think they are good for everybody, so my take on the highlights is to try to use the defaults values from idea. ex: module value is using `DefaultLanguageHighlighterColors.CLASS_NAME`. Of course there are not always a corresponding concept. 

- Option is colored differently than variant, because I like it :)

- differenciating lowercase : I think it's equivalent to https://github.com/reasonml-editor/reasonml-idea-plugin/issues/123. It's more difficult because it can't (shouldn't) be done at the lexer level.

**Comment by nirvdrum** [comment]
Re, highlighting LIDENT... I've found a couple cases that can be handled straightforwardly by inspecting AST parents. However, while I could do syntax highlighting that way easily enough, I wouldn't be introducing new `PsiElement` classes and wouldn't be updating "find usages" and friends.

Are you okay with treating those as two different problems? Or would you rather see semantic understanding propagate everywhere at once?

**Comment by giraud** [comment]
all lower identifier tokens must be PsiLowerSymbol(s). Maybe I misunderstand how intellij works, but  that's the only way I can index them and get the references. Previously I was creating specialized Psi classes for names and other, but it doesn't work. I now only work with PsiUpperSymbol and PsiLowerSymbol. Extra info that is time consuming is cached in stubs.

I don't know where you inspect the AST parent, but I think you need to look at the ORSyntaxAnnotator. This is where I would start.

**Comment by nirvdrum** [comment]
Thanks. `ORSyntaxAnnotator` is where I added my first one. I based a lot of that on the work you did several months back on variants (84766ad366cc022b24e74c38a967f21eb13319d4). But I still haven't fully wrapped my head around IntelliJ's architecture, so I was hoping to break off small chunks at a time.

**Comment by giraud** [comment]
you can contact me on the ReasonML discord app if needed.
