### ISSUE TITLE
Add documentation on how to build the plugin

### ISSUE THREAD

**Issue by nirvdrum** [reasonml-editor/reasonml-idea-plugin#183]
I was looking to provide a patch for #182, but there's no documentation on how to build and install the plugin. I think I got it, although there may be some prerequisites that I'm missing (e.g., `gradle openIdea` doesn't work).

Currently I'm running `gradle buildPlugin` and then going into the IDE to uninstall the existing ReasonML plugin and then installing `build/distributions/reasonml-idea-plugin-<VERSION>.zip`. While that works, manually loading in the plugin makes iterative development quite difficult.

If someone more familiar with the build, deploy, and test processes could document them, it'd be a great help to newcomers like me.

**Comment by giraud** [comment]
Hi, thanks for your patch.
There is a wiki section on [how to build](https://github.com/reasonml-editor/reasonml-idea-plugin/wiki/How-to-build).
you can run the plugin directly from idea, in debug mode, put breakpoints in source code or have hot reload after changes

**Comment by nirvdrum** [comment]
Wow, I'm not sure how I overlooked that. Thank you. I had pieced most of that together, but there were still a few issues:

* The default max heap was insufficient for debugging. I kept being informed I was out of memory. I think it can be fixed by adding to the `jvmArgs` list in `runIde`, but I don't really know Gradle, so that might not be the right fix.
* When running in the debug configuration, whenever I stop debugging the IDE is closed an immediately relaunched. Is there a setting somewhere to disable that? I'm not really why it's doing that.
* Where can I configure hot reloading? I'm familiar with it for conventional Java applications, but not so much for an application launched by Gradle.

**Comment by giraud** [comment]
IDE relaunch automatically when in debug is a behavior that is present with new idea versions. I don't know / search how to prevent it, I close running IDE with the kill button in the debug window:
![kill](https://user-images.githubusercontent.com/239612/64082339-be26e600-cd0d-11e9-9123-6dc25477d321.png).

hot reload happens automatically when you build the code (ctrl+F9/the hammer) unless you change a signature, or something more fundamental like the parser. You have a popup when hot reload happens:
![hot](https://user-images.githubusercontent.com/239612/64082355-0f36da00-cd0e-11e9-9bb7-c9d3f1f443b8.png)
you just have to launch the process in debug:
![debug (copie)](https://user-images.githubusercontent.com/239612/64082370-368da700-cd0e-11e9-8c12-74531d22fd85.png)

**Comment by giraud** [comment]
added xmx to jvmArgs in runIde task
