### ISSUE TITLE
IDE action for disabling automatic compilation

### ISSUE THREAD

**Issue by LosEagle** [reasonml-editor/reasonml-idea-plugin#187]
plugin version: 
0.80
### Description
Right now, disabling automatic compilation is done by adding -DreasonBsbDisabled=true into 
vmoptions file.

This solution is good enough but
1) the only way of knowing about it is to bump into issue #32 as it's not documented anywhere else
2) it's inconvenient and if one no longer needs this plugin, it stays in there in config file until new config is generated by IDE
3) this setting is not persistent and will not work if IDE regenerates config file with this added line

Perhaps it would be better to add switch into IDE actions menu itself to disable automatic compilation and simply allow us to use this plugin for autocomplete and syntax highlight.

**Comment by giraud** [comment]
env var is not documented because you can disable bsb from the settings:
![image](https://user-images.githubusercontent.com/239612/66830599-21837500-ef56-11e9-809f-7926b8dbea07.png)

**Comment by LosEagle** [comment]
I'm sorry, I didn't realize that this option only disables compilation and not the whole plugin. Thanks for response!

**Comment by giraud** [comment]
yes, it might need a better wording...
