### ISSUE TITLE
Support new refmt errors

### ISSUE THREAD

**Issue by Coobaha** [reasonml-editor/reasonml-idea-plugin#194]
plugin version: 
v0.82
### Description

Next [bs release](https://github.com/BuckleScript/bucklescript/pull/3945) will have better errors, unfortunately they are not detected by plugin. Install `bs-platform@^7.0.0-dev.1` for tests

Example of error:
```reason
let x = {
    foo;
```
error message looks like:
```reason
File "/File.re", line 14, characters 0-0:
Error: Unclosed "{" (opened line 12, column 8)
```

**Comment by giraud** [comment]
Might be linked to #174 ?

**Comment by Coobaha** [comment]
I think it is not related, `bs-platform` was only migrated to 4.06 recently

**Comment by giraud** [comment]
are you talking about the popup are the link in the console ?
popup is fine
![image](https://user-images.githubusercontent.com/239612/70514620-4cdca780-1b34-11ea-911f-c25c90fd33ab.png)

**Comment by Coobaha** [comment]
Yes, basically parsing bsb error output to intellij errors,  for me it is not working :/

IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019

```
FAILED: src/Effects.reast 
~/node_modules/bs-platform/lib/bsc.exe  -w -30-40+6+7+27+32..39+44+45+101+A-42-40-102 -warn-error +8+5 -color always -bs-jsx 3 -ppx ~/decco/ppx -ppx ~/lenses-ppx/ppx -ppx ~/ppx-deriving/ppx.js -bs-super-errors -o src/Effects.reast -bs-syntax-only -bs-binary-ast /Users/alexander/Projects/wolt/ops-tools-reasonml-modules/ops-couriers/inventory/src/Effects.re
File "~/Effects.re", line 101, characters 0-0:
Error: Unclosed "{" (opened line 99, column 8)

  We've found a bug for you!
  ~/Effects.re
  
  There's been an error running Reason's parser on a file.
  The error location should be slightly above this message.
  Please file an issue on github.com/facebook/reason. Thanks!
  
FAILED: subcommand failed.
Process finished in 915ms

```
