### ISSUE TITLE
Feature request: Autocomplete

### ISSUE THREAD

**Issue by villesau** [reasonml-editor/reasonml-idea-plugin#198]
plugin version: 0.82.1

### Description

Would be really good to have autocomplete in the plugin. Now when writing something like `Js.Di` and pressing tab, it just adds tab instead of completing it to `Js.Dict`. There is also no list of suggestions so it's not very easy to know how the API looks like.

Without auto complete it feels like driving a blindfolded.

**Comment by giraud** [comment]
Are you using 2019.3 ? 
This version breaks the indexing in node_modules.
I have a fix, but I need some cleanup and other things before publishing it.
API have changed too much with latest versions, I can't manage so many versions. I will also have to freeze development on older version than 2019 I think

**Comment by villesau** [comment]
@giraud yes 2019.3. Thanks for the quick reply! I thought it was a missing feature. My two previous bug reports might then also be related to API changes?

To be precise:

IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: Dart, Karma, com.intellij.lang.jsgraphql, com.intellij.plugins.html.instantEditing, com.jetbrains.php, com.jetbrains.plugins.ini4idea, io.flutter, net.seesharpsoft.intellij.plugins.csv, org.jetbrains.plugins.ruby, reasonml

**Comment by giraud** [comment]
I hope it is fixed with 0.83-2019.3

**Comment by villesau** [comment]
@giraud Works like a charm, thanks A lot for super quick turnaround!! Feels like I got an extra eye to my forehead.
