### ISSUE TITLE
Set OCaml SDK on the module level, not on the project level

### ISSUE THREAD

**Issue by outkine** [reasonml-editor/reasonml-idea-plugin#200]
plugin version: 0.83-2019.3

### Description
I am writing a Scala backend that has an OCaml component. In order to support both languages in IntelliJ, I set the Project SDK to `Java 1.8`, and created a module for the OCaml portion. I got this error:
```
reason: Dune: Can't find sdk.
When using a dune config file, you need to create an OCaml SDK and associate it to the project.
```
I cannot change the Project level SDK without breaking the Java portion of my backend. Is there any way to set the OCaml SDK on the level of the OCaml module?

Thank you.

**Comment by giraud** [comment]
Sorry, not now. native ocaml wasn't planned per module. I'll see how it can be changed

**Comment by giraud** [comment]
you can do it with 0.85-2019.3. UI is not very good though, you might need to open/close the dialog to see changes
