### ISSUE TITLE
New files are not indexed

### ISSUE THREAD

**Issue by Coobaha** [reasonml-editor/reasonml-idea-plugin#204]
plugin version: 
v0.84-2019.3
### Description

Steps to reproduce:

1. Create a new file
2. Navigate to old file, try to use autocompletion for new module

New module becomes visible only after invalidating caches

**Comment by Coobaha** [comment]
Or maybe my source modules are not indexed at all... I have only `node_modules` modules indexed

**Comment by Coobaha** [comment]
Problem when bsconfig has namespace

**Comment by Coobaha** [comment]
@giraud could this issue be prioritised when possible? Editor experience with namespace is so bad compared to project without a namespace

**Comment by giraud** [comment]
@Coobaha I'll look at it after current work on master is done

**Comment by giraud** [comment]
fixed in 0.86-2019.3
