### ISSUE TITLE
Tab-complete for bound components defined in tuples does not work

### ISSUE THREAD

**Issue by nirvdrum** [reasonml-editor/reasonml-idea-plugin#206]
plugin version: 0.8.4-2019.3

### Description

If I capture bindings for a tuple, like this common pattern using React's `useState` hook:

```
let (selectedRows, setSelectedRows) = React.useState(() => [||]);
```

I'm unable to tab-complete either `selectedRows` or `setSelectedRows`. Instead, the plugin suggests `(selectedRows, setSelectedRows)` as the tab completion value.

**Comment by giraud** [comment]
Duplicate of #167
