### ISSUE TITLE
bsb and refmt not running in a monorepo

### ISSUE THREAD

**Issue by giraud** [reasonml-editor/reasonml-idea-plugin#208]
plugin version: 0.85-2019.3
System: Windows

### Description

Using a monorepo on Windows OS, bsprocess and refmt are resolved to "bsb" and "refmt" instead of "bsb.cmd" and "refmt.cmd"

**Comment by Kingdutch** [comment]
The opening comment talks about Windows but I'm experiencing the same thing on OS X.

**Comment by giraud** [comment]
@Kingdutch which plugin version ? can the project be checkout ?

**Comment by Kingdutch** [comment]
It's not in public code unfortunately. I can see if I can set up a small monorepo where I can reproduce this but not sure when I'll have time to do this.

**Comment by giraud** [comment]
can you install 0.89 ?
