### ISSUE TITLE
let%private support

### ISSUE THREAD

**Issue by Coobaha** [reasonml-editor/reasonml-idea-plugin#211]
BuckleScript introduced the keyword
```
let%private x = ...
```
recently in v7.2.1-dev.1.

https://github.com/BuckleScript/bucklescript/pull/4206/files#diff-5cce8b3fd124367add92dcf6e81d49a9

It works already in that it does not export private values. However plugin still shows ident in autocompletion

**Comment by giraud** [comment]
Fixed in 0.87
