### ISSUE TITLE
Can't download rincewind

### ISSUE THREAD

**Issue by ktrzos** [reasonml-editor/reasonml-idea-plugin#212]
Newest version of plugin and PhpStorm:

```
Can't download /home/user/.PhpStorm2019.3/config/plugins/reasonml-plugin-idea/rincewind_l4.02.3-0.7.exe
java.io.FileNotFoundException: https://dl.bintray.com/giraud/ocaml/rincewind_l4.02.3-0.7.exe
```

**Comment by giraud** [comment]
sorry, should be good now

**Comment by MartynasSapoka** [comment]
I'm still seeing this on WebStorm:
`Reason
Can't download /Users/martynas/Library/Application Support/JetBrains/WebStorm2020.3/plugins/idea-plugin/rincewind_o4.02.3-0.9.1.exe
			java.io.FileNotFoundException: https://dl.bintray.com/giraud/ocaml/rincewind_o4.02.3-0.9.1.exe`

**Comment by giraud** [comment]
@MartynasSapoka yes, 4.02.3 is not really supported, I have to do some manual operations for that and I always forgot.
I updated files.
you should really update bs-platform to a version that supports 4.02.6 if possible
