### ISSUE TITLE
Strange errors/warnings even if everything is ok

### ISSUE THREAD

**Issue by ktrzos** [reasonml-editor/reasonml-idea-plugin#213]
Hello,

I'm getting these strange errors in PhpStorm 2019.3:

![Screenshot_2020-03-25_08-30-41](https://user-images.githubusercontent.com/14212721/77512427-4ff56c80-6e73-11ea-9ac5-155bcc4a8c0a.png)
![Screenshot_2020-03-25_08-29-09](https://user-images.githubusercontent.com/14212721/77512428-51269980-6e73-11ea-9a8e-332035e09f4d.png)
![Screenshot_2020-03-24_12-44-15](https://user-images.githubusercontent.com/14212721/77512430-51269980-6e73-11ea-9a76-815a8d103d85.png)

Looking at the last error, code should not even compile, but it is. My project is working fine. I even don't have any errors/warnings in the "Bucklescript" tab.

**Comment by hartmut27** [comment]
please check the  `namespace:` setting in the libararies `bsconfig.json` file.
A wrong namespace id could cause this, as Hervé's mentioning it in #236

**Comment by ktrzos** [comment]
Those warnings are occurring on modules which are a part of my projects code, so it is not related with any external library.

**Comment by giraud** [comment]
warnings numbers are now defined by ninja build file (using bs-platform >= 8.4).
