### ISSUE TITLE
Create Esy Facet

### ISSUE THREAD

**Issue by JohnPucciarelli** [reasonml-editor/reasonml-idea-plugin#217]
Differentiate between dune and esy projects by creating a separate facet for esy projects.

Currently, there is a bug when enabling esy support on the dune facet. The facet must be a newly created facet in order for esy to be activated by selecting the esy support checkbox.

Creating a separate facet for esy will remove the need for this checkbox.

@giraud do you mind creating an 'Esy' label?

**Comment by giraud** [comment]
@JohnPucciarelli you mean a github label to triage issues ?

**Comment by JohnPucciarelli** [comment]
The label will be useful for tagging any issues that come up. Also, do you have any suggestions for how I should track what I'm working on?

**Comment by giraud** [comment]
Facet created. The easiest way is to create issues and asign yourself on it I think.
