### ISSUE TITLE
IntelliJ 2020.1 is incompatible with the ReasonML plugin

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#218]
The IJ version upgrade dialog says it is incompatible, so I skipped the upgrade for now.

plugin version: 0.87-2019.3

Hope all is well.

**Comment by giraud** [comment]
Hi, I think you need to uninstall then reinstall the plugin, there is a published version for 201 https://plugins.jetbrains.com/plugin/9440-reasonml/update/82905

And thanks for asking, everything is well but time is missing for the plugin right now.

stay safe, stay home !! :)
