### ISSUE TITLE
Mishandling of "Comment with Block Comment" action (CTL-SHIFT-/)

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#22]
1. I start with this:

![image](https://user-images.githubusercontent.com/1253341/34428635-d7ec9130-ec03-11e7-9610-577a15badcac.png)

When I press CTL-SHIFT-/, the text is enclosed in /* ... \*/ rather than (* ... *):

![image](https://user-images.githubusercontent.com/1253341/34428654-052894be-ec04-11e7-8035-11f5f83d2b06.png)

2.  Sometimes I see this behavior, but I couldn't get a cut-down example with 5 minutes' trying:

![image](https://user-images.githubusercontent.com/1253341/34428683-45a4cd82-ec04-11e7-88cd-d6a469b91eea.png)

First CTL-SHIFT-/ gives the correct result:

![image](https://user-images.githubusercontent.com/1253341/34428700-68fa45e6-ec04-11e7-9c49-8eb154888dc5.png)

Doing CTL-SHIFT-/ a second time gives an incorrect result--it should remove the (* ... *):

![image](https://user-images.githubusercontent.com/1253341/34428717-92910ce6-ec04-11e7-85d4-1dbd8c5a0781.png)

**Comment by jfehrle** [comment]
For #2, try it on this:

![image](https://user-images.githubusercontent.com/1253341/34429044-ab1a0bb6-ec07-11e7-8803-1bd1d987f6cc.png)

3. If you do CTRL-/ twice on the above, you get this incorrect result when you should get back what you started with.  Looks like confusion with nested comments:

![image](https://user-images.githubusercontent.com/1253341/34429084-41feaa5a-ec08-11e7-9373-85f577a0a87e.png)

**Comment by giraud** [comment]
Should be fixed in v0.33

**Comment by jfehrle** [comment]
Yes, looks good.  Thanks!
