### ISSUE TITLE
I'm getting 100% CPU usage on Pycharm when I have this plugin enabled

### ISSUE THREAD

**Issue by JasonShin** [reasonml-editor/reasonml-idea-plugin#23]
For now, a solution to this issue is to disable the plugin while I'm not working on a reasonml project. 
I'm pretty sure you can easily reproduce this issue by installing this plugin on Pycharm and open up a relatively big enough Python code base.

**Comment by giraud** [comment]
can you give me IDE and plugin versions, please ?

**Comment by giraud** [comment]
Hi,
I'm using PyCharm 2017.3.2 CE and v0.33 of my plugin.
When opening the django project (I hope it's big enough) I don't see the CPU usage changing much.
Do you have a more precise reproduction scenario, and are you on latest plugin version ?

**Comment by JasonShin** [comment]
Hey, @giraud here is my environment details: 

Pycharm:
```
PyCharm 2017.2.4
Build #PY-172.4343.24, built on October 20, 2017
Licensed to Jason Shin
Subscription is active until August 31, 2018
For educational use only.
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13
```

reasonml-idea-plugin:

```
version: 0.32
```

**Comment by giraud** [comment]
Tried on Windows and Ubuntu. I'm not seeing any diff with or without my plugin.
Can you tell me if something change after you invalidate the caches of idea (menu: file > Invalidate caches/restat) ?

**Comment by JasonShin** [comment]
I've tried it but still same. Is it a Mac specific issue?

**Comment by giraud** [comment]
When it happens, can you look at the logs to see if there are stacktraces or messages related to this plugin ?
You can locate them by using the Help menu in idea.

**Comment by JasonShin** [comment]
Sorry I was busy, let me see if I can get the logs for you.

**Comment by giraud** [comment]
no problem, we are all busy :)

**Comment by JasonShin** [comment]
I totally forgot about this again ..! I will get this sorted out tonight sorry

**Comment by giraud** [comment]
This issue is not progressing, I'm closing it.
