### ISSUE TITLE
Very minor: incorrect comment example in Settings/Editor/Color Scheme/Reason

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#24]
The example in Settings/Editor/Color Scheme/Reason line 1 should be an OCaml comment, not /* ... */

![image](https://user-images.githubusercontent.com/1253341/34623064-84e3e860-f204-11e7-93c7-1faf144930ae.png)

**Comment by giraud** [comment]
This is not a bug, this is a ReasonML comment.

Ocaml and ReasonML are the same languages, that's why I use the same color scheme for both. 
But since I'm targeting Reason, the code in the color settings is in Reason.

**Comment by jfehrle** [comment]
Got it.  It is certainly more familiar to see /* ... */ comments.  I wonder if OCaml will adopt some of the Reason syntax improvements--which seem to have more mainstream forms, such as for function calls--or whether they will diverge more and more.
