### ISSUE TITLE
run ocamlformat on save

### ISSUE THREAD

**Issue by joprice** [reasonml-editor/reasonml-idea-plugin#240]
When using the plugin with ocaml syntax, would it be possible to add the option to format with ocamlformat on save?

**Comment by giraud** [comment]
is ocamlformat part of the sdk or do you have to install it with opam ?

**Comment by JohnPucciarelli** [comment]
I started looking into this. It needs to be installed with opam. 
https://github.com/ocaml-ppx/ocamlformat#installation

Ideally, I think the plugin should be able to install refmt and ocamlformat into its own sandbox. This isn't hard if esy is installed on the machine.

With opam, we would need to install ocamlformat globally.

**Comment by joprice** [comment]
Can it use what's on the path, if available? That way, workflows using a local switch will work, especially if projects use different versions of ocamlformat and want to make sure the ide and local formatting scripts don't conflict by undoing each other's formatting. For instance, when I use vim with ale for a quick edit, it will pick up whatever is on my path.

**Comment by JohnPucciarelli** [comment]
We can. Just means that opam or esy will need to be on the path and we'll have to check for both.

@giraud I'll take a look at how rincewind downloads and try to do something similar to execute `opam install` globally or `esy install` into a plugin-specific sandbox.

**Comment by giraud** [comment]
@JohnPucciarelli maybe we need some settings like what we have in reason ? with default values from path if found, and let user override them ? just thinking.
![image](https://user-images.githubusercontent.com/239612/80977078-8afc9f80-8e24-11ea-934e-934463366a14.png)

**Comment by JohnPucciarelli** [comment]
Read my mind. Was building exactly that yesterday. Added tabs for bucklescript, dune and esy.

**Comment by pm-mck** [comment]
If the project is identified as a dune project, could you run `dune build @fmt --auto-promote`? This would format all files dune is aware of under the `dune-project`. 

See https://dune.readthedocs.io/en/stable/formatting.html

Requires dune 2.0 to be "out of the box". With dune `>1.2, < 2.0` the `dune-project` needs some annotations.

**Comment by JohnPucciarelli** [comment]
> If the project is identified as a dune project, could you run `dune build @fmt --auto-promote`? This would format all files dune is aware of under the `dune-project`.
> 
> See https://dune.readthedocs.io/en/stable/formatting.html
> 
> Requires dune 2.0 to be "out of the box". With dune `>1.2, < 2.0` the `dune-project` needs some annotations.

Unfortunately I don't think `dune build @fmt` will work as that command formats an entire project as opposed to a single file.
