### ISSUE TITLE
Updated Webstorm to 2019.1.4 with v0.84-2019.1 not working

### ISSUE THREAD

**Issue by joegasewicz** [reasonml-editor/reasonml-idea-plugin#242]
OS: Mac, Mojave 10.14.6
plugin version: 
v0.84-2019.1
### Description

Updated Webstorm to 2019.1.4 & the reasonml-idea-plugin stopped working (the files are displayed as the default text styles). Currently have latest v0.84-2019.1 installed.
thanks

**Comment by giraud** [comment]
I've seen it recently for a mac user, don't know the root cause

**Comment by giraud** [comment]
can you update to 0.90 ?

**Comment by Coobaha** [comment]
I think IntelliJ is just disabling plugins after major version updates.. not sure what heuristics they are using but I am constantly facing this after updates

**Comment by joegasewicz** [comment]
I can confirm that reasonml-idea-plugin `0.91-2020.1` is now working as of Webstorm `2020.1.4`  so closing this issue.
