### ISSUE TITLE
missing esy sdk setup doc

### ISSUE THREAD

**Issue by joprice** [reasonml-editor/reasonml-idea-plugin#244]
plugin version:  0.88.1-2020.1

### Description

The notification here https://github.com/reasonml-editor/reasonml-idea-plugin/blob/b900903320a052d742ed5fca9571ae06852ebd75/src/com/reason/dune/DuneProcess.java#L38 points to a doc that I can't seem to find describing how to setup an esy/dune project. Is that link invalid?

**Comment by giraud** [comment]
yes, link is not updated.
the configuration "doc" is here: https://github.com/reasonml-editor/reasonml-idea-plugin/wiki/Configure-an-ocaml-project, but this is only for dune projects. esy should not need it.

**Comment by joprice** [comment]
I’m using esy and still getting that notification. How do you determine esy vs dune projects? Maybe my project is detected wrong.

**Comment by giraud** [comment]
it's a work in progress right now... esy support is not released yet

**Comment by JohnPucciarelli** [comment]
Closed by:
 - https://github.com/reasonml-editor/reasonml-idea-plugin/commit/dc752c42cc128c29653fe49258631bcc3e1e2ac3
 - https://github.com/reasonml-editor/reasonml-idea-plugin/commit/a5e3852e1a474d128cd82fdd80dcafd321ecccfa
