### ISSUE TITLE
attribute type display on CTRL+MouseOver

### ISSUE THREAD

**Issue by diablade** [reasonml-editor/reasonml-idea-plugin#245]
plugin version: not in 0.89

is it possible to add an preview or tooltip on some attribue of the html tag ? (like using : CTRL + mouse over )
for exemple here on "attributeA" or even "attributeB"  it would be great to see the input and output type)

<ComponentA
  attributeA=value
  attributeB
/>

**Comment by giraud** [comment]
Fixed in 0.94
