### ISSUE TITLE
Support .ml4 files

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#25]
Please treat .ml4 files (lexer input files) the same as .ml files.  They seem to have the same format as .ml files, although the "[<" and ">]" in match constructions may be an extension (still learning this stuff).

An example showing [< ... >]:

```
  let rec loop_symb = parser
    | [< ' (' ' | '\n' | '\r' | '\t' | '"') >] -> bad_token str
    | [< s >] ->
        match unlocated lookup_utf8 Ploc.dummy s with
        | Utf8Token (_,n) -> njunk n s; loop_symb s
        | AsciiChar -> Stream.junk s; loop_symb s
        | EmptyStream -> ()
```

**Comment by giraud** [comment]
minimal support in 0.34

**Comment by jfehrle** [comment]
Looks much better, thanks!
