### ISSUE TITLE
collapse boxes with wrong line 

### ISSUE THREAD

**Issue by diablade** [reasonml-editor/reasonml-idea-plugin#254]
plugin version: 
0.89.0.2020.1
### Description
collapse boxes [-] break with comment upon a function
collapse boxes are also not present within html tags 

![image](https://user-images.githubusercontent.com/3831334/83532912-3ca7f280-a4ef-11ea-9617-7bb0ed4529af.png)

**Comment by giraud** [comment]
Fixed in 0.90
