### ISSUE TITLE
Probable regression for jumping to a symbol

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#256]
plugin version: 0.89.0-2020.1

This version of the plugin seems to have more symbol definitions that you can't jump to with a CTRL-click on the symbol name.  In the attached file, I can't jump to `edit_rule`.  Not certain this particular symbol worked before, but there definitely seem to be more symbols you can't find this way.

**Comment by jfehrle** [comment]
[doc_grammar.ml.txt](https://github.com/reasonml-editor/reasonml-idea-plugin/files/4775732/doc_grammar.ml.txt)

**Comment by giraud** [comment]
should be fixed in version 0.92
