### ISSUE TITLE
Incorrect "</option>" JSX syntax highlighting

### ISSUE THREAD

**Issue by develop7** [reasonml-editor/reasonml-idea-plugin#262]
plugin version: 0.90.1-2020.1

### Description

Repro: type `<option>yadda</option>` in JSX context

Expected: `<option>` and `</option>` are highlighted evenly

Instead: they are not, see screenshot below

![image](https://user-images.githubusercontent.com/89889/88172498-c2ac0400-cc29-11ea-85e2-21f8d71e85c2.png)

**Comment by giraud** [comment]
Fixed in 0.92.1
