### ISSUE TITLE
ReScript Icons

### ISSUE THREAD

**Issue by JohnPucciarelli** [reasonml-editor/reasonml-idea-plugin#267]
## Feature Request

ReScript files (`.res`, `.resi`) should get their own ReScript icon.

## ReScript Brand Assets

https://github.com/reason-association/rescript-lang.org/tree/master/public/static/brand

**Comment by giraud** [comment]
I don't think it would be consistent with how file types are displayed.
current:
![image](https://user-images.githubusercontent.com/239612/92600718-38d4fa80-f2ac-11ea-804e-1c8d791cbd85.png)

**Comment by JohnPucciarelli** [comment]
Ah, didn't realize Rescript icons are already supported. Closing.
