### ISSUE TITLE
Structure panel missing function defined with "and"

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#271]
plugin version: 0.92-2020.2

The structure panel is missing `parser_of_symbol`.

![image](https://user-images.githubusercontent.com/1253341/93659347-1d2eca00-f9f9-11ea-8154-5656fa01cf29.png)

let parser_of_token_list a = 
  let loop x = () in
  ()
and parser_of_symbol b = ()

**Comment by giraud** [comment]
fixed in 0.93
