### ISSUE TITLE
Some constructor names not highlighted in function/match patterns

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#273]
plugin version: 0.93

The constructor in the pattern should be colorized and italic as it is on the right-hand side.  `Some` and `None` always seem to be correct.

![image](https://user-images.githubusercontent.com/1253341/95150876-1e246300-073e-11eb-8684-e5a228c43601.png)

type diffOpt =  DiffRemoved of string

let diffs_to_string = function
  | DiffRemoved x -> DiffRemoved "removed"

**Comment by giraud** [comment]
`Some` and `None` are special identifiers defined at the lexer level

**Comment by jfehrle** [comment]
Some of the others are highlighted, too.  But it might not be easy to highlight them all; seems it would require building a symbol table.

![image](https://user-images.githubusercontent.com/1253341/95547467-ee808f80-09b7-11eb-8560-80bf6337c2de.png)

**Comment by giraud** [comment]
should be fixed in 0.93.1
highlighting variant/modules is not easy, sometimes just a guess

**Comment by jfehrle** [comment]
Looks much better, thanks!
