### ISSUE TITLE
Omit '()' in structure panel

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#274]
plugin version: 0.93

`()` is not a name.  It's used to avoid creating a symbol.  So it probably shouldn't appear in the Structure panel.

![image](https://user-images.githubusercontent.com/1253341/95257877-d226fc00-07d9-11eb-9692-92d6446f9f83.png)

**Comment by giraud** [comment]
should be fixed in 0.93.1
