### ISSUE TITLE
Wrong modules resolution

### ISSUE THREAD

**Issue by nikshevchenko** [reasonml-editor/reasonml-idea-plugin#277]
plugin version: 0.93.1-2020.1

### Description

I have an application with @jsiebern/bs-material-ui as dependency and this my custom component:

```reason
let styles: ButtonStyles.definition = [%raw {| require("./Button.scss") |}];

[@react.component]
let make = () => {
  <button className={Cn.append(styles##button, styles##buttonSmall)}>
    "Default Styles"->React.string
  </button>;
};
```

End when I click on styles##button, IDE forward to Button componet from Material UI. 

Correct way is my custom styles.

**Comment by giraud** [comment]
fixed in 0.95
