### ISSUE TITLE
refmt action is not present anymore

### ISSUE THREAD

**Issue by Coobaha** [reasonml-editor/reasonml-idea-plugin#288]
Seems that refmt action is not available anymore?

plugin version: 
v0.95
### Description

![image](https://user-images.githubusercontent.com/2446638/101137022-d96e5880-3616-11eb-855d-fe28c199bd05.png)

**Comment by giraud** [comment]
yes, I forgot to mention it in the changelog.
it was a custom action to mimic the standard format action, but now the format code is integrated with that standard action.
you can use ctrl+alt+l or ctrl+alt+shift+l to format reason code (although there is a problem with cursor location with one of these actions)

**Comment by Coobaha** [comment]
Yes exactly, just realised that it can be formatted via normal action but scroll position is messed :D

**Comment by giraud** [comment]
yes, I'll keep that issue open for the cursor position problem
