### ISSUE TITLE
Some keywords are not highlighted in edit window

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#29]
A number of OCaml keywords are not highlighted in the editor window.  (Perhaps they are not keywords in ReasonML.)  For example, "new" should be highlighted here (which is syntactically incorrect):

![image](https://user-images.githubusercontent.com/1253341/35536056-8aa1928a-04fa-11e8-9eb5-f417069d2521.png)

Here's what I see when I copy the list of keywords from the _OCaml system release 4.06_ (https://caml.inria.fr/pub/docs/manual-ocaml/lex.html) into the edit window.  I expected all of them would be highlighted:

![image](https://user-images.githubusercontent.com/1253341/35535926-0782e336-04fa-11e8-865b-9836b32ab3ee.png)

**Comment by giraud** [comment]
Fixed in 0.36

**Comment by jfehrle** [comment]
Looks good, thanks!
