### ISSUE TITLE
"let x = function ..." should be a function in the structure panel, not a value

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#291]
plugin version: 0.94

### Description

![image](https://user-images.githubusercontent.com/1253341/101270617-79b7a080-372f-11eb-8123-aed0fd9a73a2.png)

**Comment by giraud** [comment]
Fixed in 0.96

**Comment by jfehrle** [comment]
Looks good, thanks!  And Happy New Year.
