### ISSUE TITLE
Plugin is not working with newest idea version

### ISSUE THREAD

**Issue by bkontur** [reasonml-editor/reasonml-idea-plugin#305]
plugin version:  0.96-2020.3 -> 0.38

### Description
I really like this plugin, but I would like to update plugin, but fails, I dont want to install older version of idea.
Is there any workaround? or will there be any fix for that soon?
Thank you :)

![image](https://user-images.githubusercontent.com/8159517/106299244-3bcd8900-6255-11eb-8758-33d7c557b7b1.png)

![image](https://user-images.githubusercontent.com/8159517/106299569-9a930280-6255-11eb-98a0-af43fbed544c.png)

There is also message in Idea:
```
Plugin 'ReasonML' (version '0.96-2020.3') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is IU-211.4961.30
```

**Comment by giraud** [comment]
Hi, I'm closing this issue because the plugin is never compatible with EAP.
Some older versions (until 0.38) have incorrect ranges: they have no upper revision limit.
I've updated them now so they are not proposed anymore.
I only maintain 3 versions from the latest stable version.

**Comment by bkontur** [comment]
@giraud 
Thank you very much, I did not even know what is EAP :D,
I switched to stable version and everythings works
