### ISSUE TITLE
The 'Discord' link in the README.md doesn't work

### ISSUE THREAD

**Issue by CLOVIS-AI** [reasonml-editor/reasonml-idea-plugin#306]
### Description

Nothing more to say

**Comment by giraud** [comment]
I've been redirected correctly from the README link.

**Comment by CLOVIS-AI** [comment]
On my screen (PC & Android) it redirects me to the app in a completely empty server, with no messages, no textual chats or anything, which doesn't get added to the sidebar.

**Comment by CLOVIS-AI** [comment]
The link at the bottom of the main website (https://reasonml-editor.github.io/reasonml-idea-plugin/) shows as "invalid invitation"

**Comment by giraud** [comment]
yep, website link is invalid. thanks.

**Comment by CLOVIS-AI** [comment]
Does the Discord server require an invitation of some kind? I asked someone else and it doesn't work for them either.

**Comment by giraud** [comment]
no this should be this url : https://discord.com/channels/713777184996589580

**Comment by CLOVIS-AI** [comment]
That URL doesn't work either, it leads to a group that doesn't have anything. Can you try to access it with an account that's not already in the group? It probably works for you because you're already a member.

**Comment by giraud** [comment]
the channel is not very active, but you're welcome 😄. 
the fact is I don't where to look in discord to create a link that has a correct redirection to the channel.

**Comment by giraud** [comment]
Also note that, for generic subjects that are not bugs, github discussions (https://github.com/reasonml-editor/reasonml-idea-plugin/discussions) are enabled.

**Comment by CLOVIS-AI** [comment]
Replaced by #307
