### ISSUE TITLE
nightly version?

### ISSUE THREAD

**Issue by farukg** [reasonml-editor/reasonml-idea-plugin#308]
if its possible, it would be nice to have a nightly version of this plugin via a custom plugin repository like the rust plugin offers:
![image](https://user-images.githubusercontent.com/1577842/107678843-2e27f280-6c9c-11eb-8390-b745f810739e.png)

https://intellij-rust.github.io/

**Comment by giraud** [comment]
Nope, I'm not spending time on that. sorry.
