### ISSUE TITLE
Missing icon in mli file

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#311]
plugin version: 0.98-2020.3

In the screen shot, the mli file should have an icon pointing to the second definition in the ml file (since that's the one that will be accessed from outside) and the first definition shouldn't have an icon next to it.

![image](https://user-images.githubusercontent.com/1253341/112575632-eb366000-8dad-11eb-9eb5-5cb0fbe7db6c.png)

**Comment by giraud** [comment]
Fixed in 0.98.2

**Comment by jfehrle** [comment]
Looks good, thanks.
