### ISSUE TITLE
Please alphabetize opened modules in the Structure panel

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#313]
plugin version: 0.98-2020.3

![image](https://user-images.githubusercontent.com/1253341/113457504-d0bf4080-93c4-11eb-9a1e-077b1bab968f.png)

**Comment by giraud** [comment]
Fixed in 0.98.3

**Comment by jfehrle** [comment]
Looks good, thanks.
