### ISSUE TITLE
any way to disable automatic bsb compilation?

### ISSUE THREAD

**Issue by codekiln** [reasonml-editor/reasonml-idea-plugin#32]
I'm working on a react native app with Reason, and I'd like to handle bsb compilation myself. I'd love to have some ReasonML syntax highlighting, but until ReasonReact is supported, I need to disable the ReasonML plugin looking for and attempting to do things with bsb. Is there any way to do this?

**Comment by giraud** [comment]
ok, I will add a property for that.
But may I ask you the reason why is it not working for you ?

**Comment by codekiln** [comment]
Thank you! Here's an explanation of the setup that led to this request: 

I put the following in Help > Edit Custom VM Options:

```
-DreasonBsb=/usr/local/bin/bsb
-DreasonRefmt=/Users/pnore/.config/yarn/global/node_modules/.bin/refmt
```

Then I restarted jetbrains and tried to make a new [Reason React Native Scripts](https://github.com/react-community/reason-react-native-scripts) project. I use `yarn start` to start the server, then [quit the reason react native bsb process](https://github.com/react-community/reason-react-native-scripts/issues/7#issuecomment-357127247) to try to let your plugin compile the reason. When I edit a Reason source file, I get: 

![refmt errors](https://user-images.githubusercontent.com/140930/35778179-b42b76a6-0988-11e8-98ef-4b06d33b3652.png)

In addition, in the react native server console, I get: 
```
:51:54 AM: Failed building JavaScript bundle
8:51:54 AM: Unable to resolve ../../../../lib/js/src/App" from ".//node_modules/reason-react-native-scripts/build/bin/crna-entry.js`: could not resolve `/Users/pnore/dev/react/HelloWorldRe/lib/js/src/App' as a file nor as a folder","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]},"type":"bundling_error"}"
```

If I uninstall the plugin, and do `yarn start`, then everything recompiles upon saves just fine.

So that's why!

**Comment by giraud** [comment]
It's strange, refmt is no more automatically run. what is the version of your plugin ?

I think that it's not a good idea to run bsb in a node script. The compilation phase should stay in the IDE, this way we can trigger/monitor this external compilation process. For ex, if you stop using bsb in intellij , you won't have the annotations in your sources, like here:

![hint](https://user-images.githubusercontent.com/239612/35782595-7c39b2c2-09fa-11e8-9a8c-1be728b7a54e.png)

it's not perfect yet, but it's helpful to locate the error quickly.

If you don't include neither of the bsb and remft properties, you will still get the syntax coloration.

**Comment by giraud** [comment]
in v0.38, you can use the property reasonBsbDisabled. add -DreasonBsbDisabled=true in your vm.properties file

**Comment by codekiln** [comment]
Thank you! By the way, to anyone with a similar issue that arrives here, I ended up fixing my setup to work with the plugin by removing global vmoption pointers to refmt and bsb, and instead ensuring my .bsconfig.json was correctly configured the way that I wanted. In my case, I'm using 

```
  "package-specs" : [{
    "module": "es6",
    "in-source": true
  }]
```

along with webpack, and it appears that the plugin is now correctly working with `.bsconfig.json` to compile ES6 modules that live alongside my `.re` files, which webpack then uses to create the bundles.
