### ISSUE TITLE
Icons could not be initialized.

### ISSUE THREAD

**Issue by mwerschy** [reasonml-editor/reasonml-idea-plugin#33]
plugin version: 0.38

### Description

The `com.reason.icons.Icons` class fails to initialize because the `/css/pseudo-class.png` icon was removed from the latest EAP (see [this commit](https://github.com/JetBrains/intellij-community/commit/4b625a4940caafd4842020dc92d035704c28c2e3).)

**Comment by giraud** [comment]
thanks, it'll be fix in next release

**Comment by giraud** [comment]
fix in 0.39
