### ISSUE TITLE
High CPU usage and some errors. Not all features working.

### ISSUE THREAD

**Issue by feluxe** [reasonml-editor/reasonml-idea-plugin#34]
Hi there!

When I start PyCharm with the plugin enabled, CPU usage runs up to 100% on each core for a couple of minutes. After a while it gets better.

Not all features seem to work.

These work:

* syntax highliting
* refmt shortcut
* bucklescript console

These I'm missing:

* inline error highliting.
* type annotations.

Sometimes the IDE tells me that the plugin causes errors, such as these:

```
unable to get stub builder for name.kropp.intellij.makefile.MakefileFileType@28fc9e00, , stubBindingRoot = MakefileFile, languages = [Makefile], fileTypes = [Makefile], files = [MakefileFile], roots = []

Stub index points to a file without PSI: com.intellij.openapi.fileTypes.UnknownFileType@7fbfc2da

unable to get stub builder for C++, , stubBindingRoot = PsiPlainTextFileImpl, languages = [TEXT], fileTypes = [C++], files = [PsiPlainTextFileImpl], roots = [] 
```

This is what I did in order to get the plugin running:

* install the plugin
* install bs-platform locally in the project dir, by running `npm install bs-platform --save-dev`

IDK if it matters, but `ocamlmerlin` seems to be installed globally. At least I can access it in the IDE shell.

I'm very new to Ocaml/Reason and I'm not sure where to start debugging this. Any advice would be appreciated :)

OS: Linux Arch
IDE: PyCharm

Cheers!

**Comment by giraud** [comment]
Hi,

when CPU is 100% is it during the indexing phase ? when you open your project idea index every files and it takes time and CPU power. but it should not last too much. it seems that's what happens.

For the not working features:
- inline error highlighting: it should appear asap but sometimes the editor is not refreshed. if you know there should be an annotation, you should try to synchronise files (cmd Y ?). I don't know yet why sometimes it doesn't happen.
- type annotations: for it to work you need to install bucklescript before opening the project. The plugin doesnt detect when bs is installed. Also type annotation is extracted from cmt files, so if there are compilation problems you might not have them. And last point, type annotation doesn't work yet with bucklescript namespacing.

plugin cause errors: the errors have nothing to do with my plugin, please check that plugin instead https://github.com/kropp/intellij-makefile.

**Comment by feluxe** [comment]
Thanks for your reply!

> when CPU is 100% is it during the indexing phase ? when you open your project idea index every files and it takes time and CPU power. but it should not last too much. it seems that's what happens.

I think this might be the case. I think it was related to the `node_modules` dir not being excluded from "project files".

> inline error highlighting: it should appear asap but sometimes the editor is not refreshed. if you know there should be an annotation, you should try to synchronise files (cmd Y ?).

This doesn't help.

> type annotations: for it to work you need to install bucklescript before opening the project. The plugin doesnt detect when bs is installed. 

bs-platform exists in my node_modules dir. I restarted PyCharm, without luck.

Type annotations work fine in VSCode on my machine, but I'm not sure if this is related.

**Comment by giraud** [comment]
are you editing ocaml files or reasonml files ?
is the project available so I can check ?

**Comment by feluxe** [comment]
> are you editing ocaml files or reasonml files ?

reasonml.

> is the project available so I can check ?

Yes: https://github.com/feluxe/bs-tea-starter-kit.git

    git clone https://github.com/feluxe/bs-tea-starter-kit.git

    cd bs-tea-starter-kit

    npm install

`src/Demo.re` is the file I have currently open for debugging.

Something else I have noticed is that the error highligting appears after I manually save the file.

I wonder, does the plugin fetch all binraies that it needs from the `node_modules` dir, or do I have to install anything globally on the system?

**Comment by giraud** [comment]
I'll check the project.

yes the files need to be saved to disk. when the file is saved, the plugin run a `bsb --make-world` : if the file doesn't compile the plugin try to read the error from the standard output, if the file compiles, the plugin try to read type information from the (generated) cmt file.

**Comment by giraud** [comment]
As I told you, you can't have type annotations with namespace, it doesn't work yet.
in bsconfig.json, you have `"namespace": true`.
you can have errors annotation though.

**Comment by feluxe** [comment]
Ok, thanks for clearing this! 

I don't know how they do it, but the ReasonML plugin for VSCode does the error highlighting and annotations in real time and it feels less heavy on the CPU. My subnotebook runs warm when using the idea plugin.

**Comment by giraud** [comment]
yes, type annotation is not optimized.

**Comment by giraud** [comment]
created #35

**Comment by giraud** [comment]
@feluxe can you test the performances with 0.41 please ?

**Comment by feluxe** [comment]
@giraud 
I tested it for a couple of minutes and it seems very smooth now. My laptop fan remains silent too. This is awesome! Kudos! :)
