### ISSUE TITLE
IntelliJ is extremely slow when plugin is enabled

### ISSUE THREAD

**Issue by michaelvashchinsky** [reasonml-editor/reasonml-idea-plugin#36]
plugin version: 0.40.1

### Description
Enabling the plugin make the IntelliJ extremely slow, especially for files larger than 100 LOC.

Any file: `.js`, `.ts`, `.coffee`, `.css`.

Even just scrolling is very slow and jumpy.

Disabling the plugin - IntelliJ works ok.

**Comment by giraud** [comment]
Hi, I think I have a problem with the code that display type hints.
I will try to optimise that part for the next release, or disable it until it is fixed

**Comment by giraud** [comment]
Can you please check the performances with version 0.41 and tell me if it's fixed ?

**Comment by michaelvashchinsky** [comment]
@giraud , tested on IntelliJ 2017.3.4 - no glitches!

**Comment by michaelvashchinsky** [comment]
works well also on 2017.3.5.

Thank you!

**Comment by giraud** [comment]
Thanks, closing the issue
