### ISSUE TITLE
Infered types and refmt on MacOS

### ISSUE THREAD

**Issue by lexaurin** [reasonml-editor/reasonml-idea-plugin#37]
plugin version: 0.41
os: MacOS HighSiera

Hi there,

first of all, thanks for the plugin, it's nice to see Reason integration in Webstorm. 👍  

What I'm not sure about if it's a bug or my misunderstanding of documentation is these two issues 

1. I don't see inferred types in editor, like you have on screenshots https://github.com/reasonml-editor/reasonml-idea-plugin/blob/master/docs/type.gif Is this a bug or is there some option to turn it on in WebStorm?
1. refmt is not formatting code automatically (I have to manually press ⌘⎇⇧R to reformat) while in the documentation is "**reformat (by default**, action is also mapped to crtl alt shift R)"

![screen shot 2018-03-16 at 11 11 05](https://user-images.githubusercontent.com/428302/37515340-c85923e8-290a-11e8-8a6c-15c40ed3e4f3.png)

**Comment by jsiebern** [comment]
Also if I try to open the settings it gets stuck saying "Loading..."

![macos-reason-settings](https://user-images.githubusercontent.com/6476589/37535721-da476e1e-2948-11e8-8080-136281eea629.gif)

**Comment by giraud** [comment]
Hi!

it's cool if it can help you.

1. first you need to check if your sources are compiled without errors. If you open the bucklescript window you will see the logs from the bucklescript process. Check that's ok. 
If compilation is ok, check if you are using `"namespace": true` in your `bsconfig.json`, because in this case type inference won't work (#35).

2. I dont understand what you mean.

3. loading screen: I don't know, I can't test on mac. Maybe can you do a threaddump at that moment ?

**Comment by lexaurin** [comment]
@giraud 
1. that was it. `"namespace": true` was set by `bsb -init my-react-app -theme react`. So maybe add a note about it until it is fixed? https://github.com/reasonml-editor/reasonml-idea-plugin/pull/38 
2. I mean that I'm not sure if refmt should work on WebStorms save/autosave or is it just mapped to ⌘⎇⇧R shortcut?

**Comment by giraud** [comment]
yes, you're not the first one to be confused.

**Comment by lexaurin** [comment]
I see. Thanks for info.

**Comment by giraud** [comment]
Color settings fixed in 0.42

**Comment by Coobaha** [comment]
Hi @giraud,

in 0.43 `refmt` command is not working
![image](https://user-images.githubusercontent.com/2446638/37824894-81c83a66-2ea7-11e8-8fcd-27a67e20c019.png)

**Comment by giraud** [comment]
I've created an issue to follow that problem #40
