### ISSUE TITLE
Plugin checks on OCaml syntax, not Reason

### ISSUE THREAD

**Issue by acierto** [reasonml-editor/reasonml-idea-plugin#4]
I've installed reason-cli, added all paths to my VM options

-DreasonBsb=node_modules/bs-platform/bin/bsb.exe
-DreasonMerlin=/Users/bogdannechyporenko/.opam/4.02.3/bin/ocamlmerlin
-DreasonRefmt=/usr/local/bin/refmt

I have ocamlmerlin-reason in my path
[
<img width="562" alt="screen shot 2017-07-11 at 21 00 46" src="https://user-images.githubusercontent.com/2265094/28085450-0fd75d0e-667c-11e7-8351-4402e17248d4.png">
](url)
but plugin still checks it on OCaml syntax, not Reason.

<img width="472" alt="screen shot 2017-07-11 at 21 07 16" src="https://user-images.githubusercontent.com/2265094/28085740-f263245a-667c-11e7-9ea0-abe892560a4b.png">

Where can be the problem?

OS: MacOS
Merlin 2.5.4
Ocaml 4.02.3

**Comment by giraud** [comment]
Sorry, on holidays until august.

**Comment by acierto** [comment]
Ok, seems like running `idea .` in iterm should help.
But I have so many other issues with that plubin, that can't verify that it actually helps:
https://github.com/reasonml-editor/reasonml-idea-plugin/issues/6
https://github.com/reasonml-editor/reasonml-idea-plugin/issues/7
Though I don't see syntax error of arrows in function, so that's promising :)
