### ISSUE TITLE
Recursive types are not resolved correctly for autocompletion

### ISSUE THREAD

**Issue by jsiebern** [reasonml-editor/reasonml-idea-plugin#41]
plugin version:  `0.43`

### Description

Take a look at this image:
<img width="1516" alt="00000031" src="https://user-images.githubusercontent.com/6476589/37908782-7157cffc-3109-11e8-9b13-61400b0792ae.png">

The file on the right hand side is called `Types` where I defined a module `Data` and a recursive type `splitTest ... and splitTestVariant`. The `splitTestVariant` one is not displayed in the autocompletion as seen on the left.

There are also entries shown which are located in another module called `Helpers` (the convertXXX methods) (so submodule `Helpers.Data`). It seems that the name `Data` acts as a global module, not a submodule.

Other than that: Great update, I really enjoy using the plugin by now 👍 (Only thing I believe I'm missing is the Standard Lib completion (`Js.xxx`, `Belt.xxx`)!

**Comment by giraud** [comment]
Thanks for the report.

First, keep in mind that completion is an ongoing work and is lacking a lot of functionalities.
That being said, issues like this one helps me a lot.

You should already have Js completion (but you must type `Js.` manually).

**Comment by giraud** [comment]
Hi, can you try with 0.44 ?

**Comment by jsiebern** [comment]
Awesome, that fixed it completely! Also `Belt.xxx` is now working, but `Js.xxx` still won't work for me unfortunately.
<img width="489" alt="2018-03-29_1202" src="https://user-images.githubusercontent.com/6476589/38083131-0a1b81c0-3349-11e8-8229-9d1c8c5f6385.png">

But that's not a big deal, I know most of those by heart anyway, thank you so much for fixing the other problems!

**Comment by giraud** [comment]
That's not normal 😬.

When you call the completion popup on a whitespace, do you see Js module in the list ?
![image](https://user-images.githubusercontent.com/239612/38085069-7a362496-334f-11e8-899f-9cb30c082cf8.png)

Do you have another custom Js module in your project ?

**Comment by jsiebern** [comment]
Please don't ask why, but I tried it outside of a function scope and it worked. Then I tried it inside again and it suddenly works. Beats me 😅

It works now anyway, thank you so much for your hard work

**Comment by jsiebern** [comment]
On another note: I also have one of my packages called `@jsiebern/bs-devextreme-reactive` in my `bsconfig.json`, and another one called `@jsiebern/bs-material-ui`.

The `material-ui` one has `namespace: false` and works after I manually type `MaterialUi`. The other one has `namespace: true` and does not even autocomplete after typing `JsiebernBsDevextremeReactive`. Maybe namespaced packages are not taken into account yet when `namespace` is `true` 😊?

**Comment by jsiebern** [comment]
Though it correctly annotates its usage it seems:

<img width="623" alt="2018-03-29_1438" src="https://user-images.githubusercontent.com/6476589/38089227-faeaf9cc-335e-11e8-8d45-a385856f6887.png">

**Comment by jsiebern** [comment]
Oh, and while we're at it (sorry!): The click to jump feature does the same thing as the autocomplete did before with submodules I believe.

When clicking the `UI` in `Helpers.UI.xxx` it jumps to the `Types.UI` instead.

**Comment by giraud** [comment]
is your project open source ?
namespace is still broken, I'm still not sure how it work in bs

**Comment by giraud** [comment]
> Wait, sorry, I was being really dump, I was in VSCode by mistake
lol 😆

**Comment by giraud** [comment]
fixing the goto action might take more time

**Comment by giraud** [comment]
can you check that the file `bs-platform/lib/ocaml/js.mli` exists ?

**Comment by jsiebern** [comment]
Hm, it actually does not, it's a fresh install of `bs-platform` too, so not sure what's going on... (And theres no other `Js` module in my project either)

Yes, my bindings with that namespace are open source: 
https://github.com/jsiebern/bs-devextreme-reactive

**Comment by giraud** [comment]
quick update: I fixed the goto actions, but I found several parsing problems with your sources. I'm fixing them before a new release.

**Comment by jsiebern** [comment]
Nice one on the goto actions 👊! I'm looking forward to that release, thank you so much for the awesome work you do!

**Comment by giraud** [comment]
I've released 0.45

**Comment by jsiebern** [comment]
Ha, I was about to tell you that it crashes my IDE 😅 Thank you!!

**Comment by jsiebern** [comment]
0.45.1 does the same :-( 

Does this help?

[threadDump-20180410-151036.txt](https://github.com/reasonml-editor/reasonml-idea-plugin/files/1894683/threadDump-20180410-151036.txt)

**Comment by giraud** [comment]
panic mode here :)
I'm so sorry, I have difficulties finding a way to detect cmi changes that can also work on mac, and I can't test it.
can you please test 0.45.2 when possible? I totally deactivated the directory watcher.

**Comment by jsiebern** [comment]
Don't worry, you're doing this on your own time and I appreciate it a **lot**!! `0.45.2` does not crash :)

**Comment by jsiebern** [comment]
Let me know if you want me to test something "live", we can get in touch on Discord / Skype or whatever if it helps you at all!

**Comment by giraud** [comment]
neh, not yet, I have to rethink the way to do it. pff.
at least it doesn't crash idea 👍

**Comment by giraud** [comment]
are you on the reasonml discord server ? I have a beta to be tested.
