### ISSUE TITLE
Apply for opencollective

### ISSUE THREAD

**Issue by blackxored** [reasonml-editor/reasonml-idea-plugin#48]
I know this is not that popular, but I'd assume some people (myself included) would want to contribute to this project any way they can; towards the goal of making this as feature-full as the VSCode extension and even more. 
Here's the link: https://opencollective.com/opensource/apply

**Comment by giraud** [comment]
Hi, I don't know open collective: why do you say it is not popular ?
I don't feel legitimate to open a collective: this is a small project and it seems irrealistic to ask money for that.

**Comment by blackxored** [comment]
By “not popular” I meant Reason/this plugin. The second part of the
argument, in my eyes you wouldn’t be “asking for money”, but enabling
people like myself to contribute. In my particular case, I can’t quite with
code but I’d very much love this project moving forward. Sorry if wishful
thinking.

-- 
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by giraud** [comment]
no problem.
I'm open to proposals, but I'll have to read the legal information, it might be more difficult for people living in europe maybe.

**Comment by giraud** [comment]
lol! I tried OpenCollective, but I'm not there yet :smiley: 
![stars](https://user-images.githubusercontent.com/239612/39330265-56520dde-49a1-11e8-8cb6-87e4c44c3cbb.png)

**Comment by blackxored** [comment]
Oh darn. You can switch to Patreon or wait on stars 😞

**Comment by giraud** [comment]
I created an account on liberapay: https://liberapay.com/hgiraud. I'll see how it goes.

**Comment by blackxored** [comment]
Nice. I signed up and it eventually worked. It's a bummer it doesn't support PayPal, but hey.

**Comment by giraud** [comment]
Awesome! You rock. Thank you very much.
