### ISSUE TITLE
Color scheme bug in JSX Tag

### ISSUE THREAD

**Issue by jsiebern** [reasonml-editor/reasonml-idea-plugin#52]
plugin version: `0.48.1`

### Description

Just a small color scheme bug:
<img width="262" alt="2018-05-03_1404" src="https://user-images.githubusercontent.com/6476589/39575603-72d9360a-4edb-11e8-8fdf-756b8b3d0ed6.png">
The color in the closing tag differs when using nested modules.

Not important but I still thought it worth reporting :-)

**Comment by giraud** [comment]
Fixed in 0.51
