### ISSUE TITLE
Intention to add braces (block) for blockless functions

### ISSUE THREAD

**Issue by Coobaha** [reasonml-editor/reasonml-idea-plugin#53]
Hi! Thanks for this plugin!

It is very painful to edit oneline functions, would be lovely to have intention for this, like in JS
![image](https://user-images.githubusercontent.com/2446638/39584986-61572312-4efc-11e8-8fc1-3d913c20a31f.png)

**Comment by Coobaha** [comment]
Another use case is to auto swap parentheses to braces in 
```
Array.(
  ...
)
```

**Comment by giraud** [comment]
Thanks for the suggestion.
I don't know yet if and how I can do it.

**Comment by giraud** [comment]
It was not hard, after all:
![addbraces](https://user-images.githubusercontent.com/239612/40236029-7a3dc9a6-5aac-11e8-97ab-3d5f54e2bb2f.gif)

**Comment by giraud** [comment]
implemented in 0.52

**Comment by Coobaha** [comment]
@giraud 
I have found 2 issues so far
![untitled](https://user-images.githubusercontent.com/2446638/40622399-19a7c9ba-62aa-11e8-8ce7-b72c13432c77.gif)
1. top function body is used instead of inner
1. curly braces position, starting brace could be same line as function declaration, end brace - new line after function end. This one is not very important but could provide better experience

**Comment by giraud** [comment]
1. good catch, will look at it
2. The first implementation was inserting new lines, but I hit some problems and reverted. I don"t have time to investigate

**Comment by Coobaha** [comment]
@giraud in 0.53 i found this bug with local open intention
![open](https://user-images.githubusercontent.com/2446638/40823160-fa017fcc-6577-11e8-851c-aa6b3e658297.gif)
