### ISSUE TITLE
Go to function definition

### ISSUE THREAD

**Issue by tigp** [reasonml-editor/reasonml-idea-plugin#54]
plugin version: 0.49

Thanks so much for the work you've done, it's really incredible, it seems to work even better than VSCode, especially Bucklescript panel and syntax checking!

### Description

I'm not sure if it's not implemented yet or I misconfigured something, the problem is that I can go to definition to the module like ReasonReact but can't go to the function it contains. What could be the problem?

Thank you so much again!

**Comment by giraud** [comment]
Thanks for the comment.
go to is not working because.... it is not implemented yet :smile: 
I am referencing too much functions right now for the action to be usable, I need to filter results more.
I know it can be really frustrating, I,m looking at a solution.

**Comment by tigp** [comment]
That's really great to hear that it's on your list. Thank you again for investing your time to work on this great plugin!

Have a great day!

**Comment by Coobaha** [comment]
@giraud 
I have noticed that Go to works incorrectly in this case:
```
// my project file
module Module = {
  let value = 1;
};
Module.value; /* cmd+click (ctrl on win?) in Module is buggy */
```

It jumps to `node_modules/bs-platform/vendor/ocaml/ocamldoc/odoc_info.mli`

```
module Module :
  sig
...
```

**Comment by giraud** [comment]
I think it is the same problem than in 56

**Comment by giraud** [comment]
Go to function should work in 0.56, at least for externals and lets.
you can open new issues on more specific use cases.
