### ISSUE TITLE
Facet configuration not available in Webstorm

### ISSUE THREAD

**Issue by jsiebern** [reasonml-editor/reasonml-idea-plugin#55]
plugin version: 0.49

### Description

I can't use the latest update in PHPStorm / Webstorm as these editors don't have facets. The plugin still works, but only if the `bsconfig.json` is actually located at the root folder of my project (which in my case it's not, but rather in `sources/bsconfig.json`.

I'll downgrade for now or try to move my `bsconfig.json`.

**Comment by giraud** [comment]
I found the ProjectConfigurable extension in idea SDK, I'll try to use it in next release.

**Comment by giraud** [comment]
No more facets, they can't be used outside IDEA.
https://github.com/reasonml-editor/reasonml-idea-plugin/wiki/Configure-a-bucklescript-project
Settings can be configured per project now

**Comment by jsiebern** [comment]
Awesome, thank you for your quick reaction, it works perfectly now :-)
