### ISSUE TITLE
Autocompletion uses additional sources

### ISSUE THREAD

**Issue by jsiebern** [reasonml-editor/reasonml-idea-plugin#56]
plugin version: 0.48.1

### Description
I have some additional sources defined for autocompletion in PHP (I'm using PHPStorm), in the language settings for PHP like so:
![2018-05-06_1231_dirs](https://user-images.githubusercontent.com/6476589/39672404-e38599fc-5129-11e8-81bf-2120c488c7cc.png)

It seems that the autocompletion takes those into account / favors them over the local install:
<img width="561" alt="2018-05-06_1231" src="https://user-images.githubusercontent.com/6476589/39672414-f07d07ee-5129-11e8-9b01-483e8dcd3e27.png">

The `ReactJsonTree` isn't even part of the current project!

Maybe it would make sense to limit the autocompletion sources to the local `node_modules` and folders defined in `bsconfig.json`?

**Comment by giraud** [comment]
> Maybe it would make sense to limit the autocompletion sources to the local node_modules and folders defined in bsconfig.json?

it is the idea, I got something wrong

**Comment by giraud** [comment]
but I didn't released it yet !

**Comment by jsiebern** [comment]
Whoops, I didn't notice it in the latest version so I thought this was done 😂
