### ISSUE TITLE
Setting for using `-make-world`

### ISSUE THREAD

**Issue by jsiebern** [reasonml-editor/reasonml-idea-plugin#57]
### Description

A little more control over Bucklescript would be amazing, I was thinking about something like:
- A settings option for choosing `bsb` or `bsb -make-world` on save
- A hotkey for calling `bsb -clean` and / or `bsb -clean-world`

Just convenience functions but maybe worth implementing :-)

**Comment by jsiebern** [comment]
Wow, my bad, I never realized! That button is all I need, thank you 👍

**Comment by giraud** [comment]
added a small entry in wiki: https://github.com/reasonml-editor/reasonml-idea-plugin/wiki/Bucklescript-compiler
