### ISSUE TITLE
Its not possible to use  'reasonBsb' and 'reasonRefmt'

### ISSUE THREAD

**Issue by Coobaha** [reasonml-editor/reasonml-idea-plugin#58]
HI @giraud!
After #47 and revert of it in #55 it's not possible to set custom `refmt` and `bsb` paths anymore. Should this be possible again too?

P.S. It would be nice to set `refmt` default width for all projects (now it is set per project only) or at least match the default one.. because with every new reason project opened in IntelliJ there is a need to change it to be 80 (standard) from 120 (plugin default)..

**Comment by giraud** [comment]
Hi, 
I'm not sure to understand you.
You can set custom bsb path in the settings: use `Settings | Languages & Frameworks | Reason`.
refmt must be from the same bs-platform version, so it uses the custom bsb path.
The jvm properties were a hack until a settings page was done.

**Comment by Coobaha** [comment]
Right, thanks
