### ISSUE TITLE
Colored output in Bucklescript tab

### ISSUE THREAD

**Issue by blackxored** [reasonml-editor/reasonml-idea-plugin#59]
plugin version: 0.50

### Description
Bucklescript window doesn't have colored output which makes visually scanning through errors a bit trickier.

**Comment by giraud** [comment]
yes, see this issue https://github.com/BuckleScript/bucklescript/issues/2735

**Comment by giraud** [comment]
fixed in v0.60.2.
Note that you need bucklescript v4.02+
