### ISSUE TITLE
Plugin sends incorrect flags to refmt

### ISSUE THREAD

**Issue by acierto** [reasonml-editor/reasonml-idea-plugin#6]
If I press Cmd-S I see such error:

<img width="590" alt="screen shot 2017-08-12 at 12 07 47" src="https://user-images.githubusercontent.com/2265094/29239790-14e00ab4-7f57-11e7-95ba-d6e39ed1f00e.png">

And obviously no reformatting occurs.

**Comment by giraud** [comment]
fixed in 0.11.
always use refmt with double dash
