### ISSUE TITLE
graphql_ppx code gets confusing hints

### ISSUE THREAD

**Issue by Coobaha** [reasonml-editor/reasonml-idea-plugin#63]
plugin version: 
**0.51**

### Description
This can be reproduced here https://github.com/Coobaha/reasonml-idea-plugin-graphql-ppx-issue

![image](https://user-images.githubusercontent.com/2446638/40252285-9729300e-5ae4-11e8-8182-8b0594824898.png)

**Comment by giraud** [comment]
yes, the ppx makes things confused.I'm not even sure what the correct types are.

**Comment by giraud** [comment]
In 0.722, display the signature of the generated 'make' function.
