### ISSUE TITLE
End_of_file exception

### ISSUE THREAD

**Issue by acierto** [reasonml-editor/reasonml-idea-plugin#7]
Just open project and immediately see an exception:

<img width="1038" alt="screen shot 2017-08-12 at 12 10 11" src="https://user-images.githubusercontent.com/2265094/29239810-5acb269e-7f57-11e7-9b0c-b614e99cabb3.png">

Reproducible on this one: https://github.com/acierto/ts-explorer

**Comment by giraud** [comment]
which version of plugin are you using ?

**Comment by acierto** [comment]
That was with 0.10, what was the latest at that time.
I see that you released 10 min ago 0.11 - the issue is still there. 
You can easily reproduce it if you will clone the project I mentioned in the original issue.

**Comment by giraud** [comment]
I tried with https://github.com/reasonml/reason-cli beta-v-1.13.6 but didn't reproduce it.
I will retry later

**Comment by acierto** [comment]
Please use this repo to reproduce the issue: https://github.com/acierto/ts-explorer
The issue with 0.12 still there. Don't know about beta-v-1.13.6, it is not available in Intellij IDEA repository.

![screen shot 2017-08-18 at 09 36 49](https://user-images.githubusercontent.com/2265094/29448904-f27a736e-83f8-11e7-9440-372ad6fbb085.png)
![screen shot 2017-08-18 at 09 36 40](https://user-images.githubusercontent.com/2265094/29448903-f27a5500-83f8-11e7-83be-c88994aa5cc1.png)

**Comment by giraud** [comment]
how did you install merlin and which version are you using ?
I installed merlin by following the linux instructions that can be found here [https://github.com/reasonml/reason-cli](https://github.com/reasonml/reason-cli). beta-v-1.13.6 is the version of the reason-cli I am using.
Can you try again with reason-cli ?

**Comment by acierto** [comment]
That's exactly how I installed.
We are talking with you about different versions. I'm talking about the version of your plugin and you  are about the version of reason-cli version.

**Comment by giraud** [comment]
good, so we are using the same versions.
The error is that merlin returns an error response because it can't process a file. The problem is for me to reproduce the error with your repo, it didn't happen yet.

**Comment by acierto** [comment]
That's quite interesting, because with the latest plugin 0.12, I have an infinite error.
I even tried right now, just to do git clone  of the repo to another folder, npm install, and see this :)
![screen shot 2017-08-21 at 15 01 12](https://user-images.githubusercontent.com/2265094/29520542-bff97ee0-8681-11e7-8928-ac5e5438fbb4.png)

**Comment by giraud** [comment]
I'm sorry about that. My problem is that I can't reproduce it on my environment.
I created a new version that doesn't report merlin exceptions to the user. 
Can you try it when available ? it's v0.16

**Comment by giraud** [comment]
Ok, my communication code was stupid.
I changed it a little bit ; it's not perfect but if you update to v0.17 the merlin process should not generate errors anymore... or I hope so.

**Comment by acierto** [comment]
Hey,
I still see after 4 days the latest version of your plugin v0.15

<img width="728" alt="screen shot 2017-08-25 at 19 17 12" src="https://user-images.githubusercontent.com/2265094/29724773-21f3f5ee-89ca-11e7-9768-a7ff5804484f.png">

**Comment by giraud** [comment]
When the button is blue, click on it, you will get the latest.

**Comment by acierto** [comment]
yeah, true, looks like Intellij IDEA caches the version, and shows not the latest version.
So, I installed v0.18 and now I see another issue>
<img width="1260" alt="screen shot 2017-08-25 at 19 33 29" src="https://user-images.githubusercontent.com/2265094/29725474-8aa29f4e-89cc-11e7-9cc5-ad4e76880406.png">
<img width="797" alt="screen shot 2017-08-25 at 19 34 02" src="https://user-images.githubusercontent.com/2265094/29725473-8aa1c0b0-89cc-11e7-9d4d-be2299926ed0.png">

**Comment by giraud** [comment]
can you file another bug please ?

**Comment by acierto** [comment]
moved to https://github.com/reasonml-editor/reasonml-idea-plugin/issues/8
