### ISSUE TITLE
Code lens issues

### ISSUE THREAD

**Issue by blackxored** [reasonml-editor/reasonml-idea-plugin#70]
plugin version: 

### Description

Can we display code lens above the line instead of next to it? Like VS Code?
Also, I realize it's prob an arch issue, but it seems like in lenses IDEA's uses Ocaml syntax for displaying it regardless of the file type.

**Comment by giraud** [comment]
Hi, no this is not possible. IDEA doesn't allow to create new lines just for annotation.
type inference is extracted by reading cmt files: these files are always created from ocaml (.re -> refmt -> .ml -> bsb -> .cmt). Type signature is OCaml flavor.
I tried to convert them, but it would generate errors so I just display the ocaml version for now

**Comment by blackxored** [comment]
Hi,
I'm almost sure I've seen something like this in IDEA while working on Scala a few years back, although I can't quite make the name of the feature (decorators comes to mind but that's probably just plain wrong). 
I think the type hint issue is rather confusing if you're not working in OCaml, wonder how VSCode does it (it correctly shows Reason signatures on .re files and Ocaml signatures on .ml).

**Comment by giraud** [comment]
If you can find a plugin that does it, send me a pointer.
type signature: maybe they call refmt again on type signature to transform them to reason ? but that has a cost in term of perfs
