### ISSUE TITLE
Modules defined in .ml files don't appear in the Structure panel

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#75]
plugin version: 0.57

### Description

The module definition "VCS" is missing from the Structure panel.  Symbols defined in the module should appear as subnodes under "VCS".

![image](https://user-images.githubusercontent.com/1253341/42414926-56a29376-81f5-11e8-924c-26ce2130a9dc.png)

**Comment by giraud** [comment]
should be fixed in 0.60.1

**Comment by jfehrle** [comment]
Hi Hervé, the 3 fixes in 0.60.1 related to my bug reports look good, thanks!
