### ISSUE TITLE
When the plugin is enabled, IntelliJ becomes unresponsive/reports out of memory when using global find

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#76]
plugin version: 0.57
IJ Community Edition 2018.1.5

### Description

When the plugin is enabled and I use the global find function, IntelliJ becomes unresponsive (several seconds delay for trivial screen updates) and reports it is out of memory, suggesting that you increase the memory limit.  The CPU use for IntelliJ also jumps way up (more than 80% on my 4 HW thread system).  Perhaps something is being done in the Swing thread that should not be there?

What I'm doing to see this behavior is a repeated global find:
- select a string in an editor window
- press CTRL-SHIFT-F to do a global find
- click in the lower panel of the find dialog, select another string
- press CTRL-SHIFT-F to do another global find with the new string
and perhaps repeat the last two steps a few times.

All too easy to reproduce.  I had to disable the plugin to do any work.  I may switch back an earlier verison of IJ that has an older version of the plugin--I don't see any other way to switch to an older version.

If you can verify this behavior but the fix is not a quick one, maybe you could back out the 0.57 version until there is a fix?

**Comment by giraud** [comment]
There are some flaws in the OCaml parser that generate too much recursion. 
You should try 0.57.1 and tell me if it's better: I updated the parser and added some guard on the path finder.

**Comment by jfehrle** [comment]
It seems to be working normally now, thanks!
