### ISSUE TITLE
Show non-alphanumeric function names such as ">>=" in the structure panel

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#77]
plugin version: 0.57.1

### Description

It would be nice to someday show the `>>=` and `>>` in the structure panel.  (Highlighted in yellow below.)

![image](https://user-images.githubusercontent.com/1253341/42546898-521e3194-8474-11e8-8f3f-2368da0be331.png)

**Comment by jfehrle** [comment]
Just updated to 0.58 and I see no change in behavior.  Perhaps it's related to modules?  Here's the full file I used in the example: [monad.ml.gz](https://github.com/reasonml-editor/reasonml-idea-plugin/files/2193005/monad.ml.gz)

**Comment by giraud** [comment]
The commit automatically closes the issue, but it'll be in next release
