### ISSUE TITLE
Let symbol missing in structure panel

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#78]
plugin version: 0.58

### Description

"extern_reference" should appear in the structure panel.  (At interp/constrextern.ml:280)

![image](https://user-images.githubusercontent.com/1253341/42742061-c7dee26a-8885-11e8-98c3-6cef6578ccfc.png)

**Comment by giraud** [comment]
fixed in v0.59.1
