### ISSUE TITLE
 Can not deserialize instance of java.lang.Boolean out of START_ARRAY token

### ISSUE THREAD

**Issue by acierto** [reasonml-editor/reasonml-idea-plugin#8]
<img width="1260" alt="screen shot 2017-08-25 at 19 33 29" src="https://user-images.githubusercontent.com/2265094/29725814-c0a7a282-89cd-11e7-9135-ca80a92abcf0.png">

**Comment by giraud** [comment]
I'm closing that issue because now the plugin is using merlin 3 and have a different json decoding code.
Open a new bug if this problem persist with plugin 0.19+
