### ISSUE TITLE
Enhancement: Support GoTo/Implementation(s)

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#81]
plugin version: 0.58.1

### Description

GoTo/Declaration takes you to the declaration of a symbol in the .mli file.  It would be very handy to have a way to jump to the implementation in the .ml file, such as GoTo/Implementation(s) (highlighted in the screen shot and doesn't do anything at the moment).  Also, FWIW, GoTo/Type Declaration doesn't do anything at all, maybe should be disabled?

FWIW, "Implementations" was probably meant for finding all the subclasses of a class (if a class is selected) or the overriding implementations of a method in subclasses (if a method is selected).

![image](https://user-images.githubusercontent.com/1253341/42914692-b7740414-8ac9-11e8-9381-3277fb80f560.png)

**Comment by jfehrle** [comment]
I hope you get to work on this soon.  It's pretty odd that I can jump the to declaration in the `.mli` file and all the usages, _but I can't jump to the definition in the_ `.ml`!

![image](https://user-images.githubusercontent.com/1253341/81026322-90f77e00-8e2e-11ea-956c-307279a8985d.png)

**Comment by giraud** [comment]
sorry for the delay.

**Comment by jfehrle** [comment]
No worries.  One other detail is that the very convenient control-clicking on a symbol takes you to the .mli and not the .ml--usually not what I want.  I'm conditioned to use that because in Python code, it takes you the definition of a method.

**Comment by giraud** [comment]
should be fixed in version 0.92
