### ISSUE TITLE
Bug/Enhancement: Support GoTo/Declaration for function-local symbols

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#83]
plugin version: 0.58.1

### Description

GoTo/Declaration doesn't find function-local symbols.  For example, it doesn't find "lex", which is defined on the previous line.  And it should know it's a local symbol (the tooltip suggests it did a global search).

![image](https://user-images.githubusercontent.com/1253341/42915340-5f478618-8acd-11e8-9bc6-e28ba8c87227.png)

**Comment by jfehrle** [comment]
I found a bug in 0.60.1 related to not distinguishing local and global symbols.  In the following code, when I GoTo/Declaration on `output` on the last line below, the plugin incorrectly takes me to the `output` definition in Pervasives.mli.  That's misleading, not useful behavior.

```
let diff_hyps o_line_idents o_map n_line_idents n_map =
  let output old_ids_uo new_ids = <omitted>

  output (List.rev o_idents) []
```

**Comment by jfehrle** [comment]
Regarding the original example, it might be overwhelming to show every local symbol in the structure panel.  IIRC, older versions of IntelliJ had filtering options to control whether to show variables (for Java code).  On the other hand, if a local symbol is a function, I think I would want to see it in the structure panel in any case.

**Comment by jfehrle** [comment]
Great! That works much better, thanks!

What do you think about showing nested function definitions in the structure panel, such as `output` in the second example?  I tend to used nested definitions often to keep my code organized.

I can put in a new request for that if you're open to that.

**Comment by giraud** [comment]
@jfehrle I'm not a fan of showing every items in the structure. But please, add a feature request in github for that. I don't know maybe if I can add an icon in the structure panel to enable that feature it could be ok. I don't know how other languages do it.
