### ISSUE TITLE
Functions missing in structure panel

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#84]
plugin version: 0.58.1

### Description

A number of functions are missing from the structure panel.  For example, for the following file, the second function doesn't appear in the list.  In my original file, it omits about 10 in a row but not the entire file.  Removing the "Pp.(...)" idiom makes the subsequent functions appear.

```
let can_enable_diffs () =
  CErrors.user_err Pp.(str "Error: Color must be enabled (\"-color on\" in the command line) to show diffs")

let write_diffs_option () = true
```

**Comment by giraud** [comment]
should be fixed in 0.60.1
