### ISSUE TITLE
Undo after saving (refmt) doesn't work

### ISSUE THREAD

**Issue by jsiebern** [reasonml-editor/reasonml-idea-plugin#85]
Opening an issue about this as just discussed.

When saving a file and having `refmt` run automatically, it becomes impossible to undo the last changes.

**Comment by pm-mck** [comment]
Hi @giraud! Is it possible to help or somehow prioritize this issue (bounty, etc)? When it happens while I'm working on OCaml code it seemingly randomly destroys the formatting, totally rewrites the code, and makes it impossible to recover. It happens even if I have `Reformat on save` disabled in the settings.

I love this plugin, but this just bit me again and it _really_ sucks when it happens. Let me know how I can help.

**Comment by giraud** [comment]
@pm-mck I'm sad to know that it still cause problem.
first I need to be sure that auto-fmt can be disabled. you need to create a new issue about auto fmt with plugin version and if possible, the context and a repro case, I'll work on it. and also if possible another issue with the undo problem.

**Comment by pm-mck** [comment]
Here you go #148 Thanks again!

**Comment by giraud** [comment]
Reopen that issue if needed (with some context), but I can't reproduce it.
