### ISSUE TITLE
[Reformat on save] always reformats the code regardless user settings

### ISSUE THREAD

**Issue by unodgs** [reasonml-editor/reasonml-idea-plugin#86]
plugin version: 0.59

### Description

IDE always reformats my code on save - even if formatting on save is disabled

**Comment by giraud** [comment]
strange, can you confirm that the checkbox of settings is unchecked ?
![image](https://user-images.githubusercontent.com/239612/43183527-b6da1fd6-8fe5-11e8-9d30-3fb42cbfbec3.png)

I tried it on my project and it seems to work: any particular project structure ?

**Comment by jsiebern** [comment]
I believe that I experienced the same thing and was pulling my hair until I realized I still had the Flag in the vm-options set for when that feature was in beta!

**Comment by giraud** [comment]
Oh man is that possible ? It shouldn't be, I need to check.

**Comment by unodgs** [comment]
Yes, I'm sure I have it unchecked:
![image](https://user-images.githubusercontent.com/7407/43214972-31333574-903b-11e8-8d5f-9bbe54a4adf8.png)

**Comment by Coobaha** [comment]
maybe it's the same issue as #69? @unodgs do you have multiple open projects?

**Comment by giraud** [comment]
I'm closing this issue because I reworked how compiler and refmt are instanciated in 0.65.
But I'm still not sure it is really fixed.

**Comment by unodgs** [comment]
It worked for a while but from some time it started to reformat on save again :( I have reformat unchecked. Could you please reopen this bug?

**Comment by unodgs** [comment]
Looks like everything works fine again in version `0.87.1-2020.1-EAP1` Thx!
