### ISSUE TITLE
Renaming variables doesn't work

### ISSUE THREAD

**Issue by simeg** [reasonml-editor/reasonml-idea-plugin#89]
plugin version: 0.59.1

### Description
When I use the built-in tool to rename a variable, everything seems ok at first but when I press enter to perform the action it says "No occurrences found". Let me know if you need more info.

![variable_refactor](https://user-images.githubusercontent.com/8566054/43365491-03238ce2-932e-11e8-9ae7-1615b092ac97.gif)

**Comment by giraud** [comment]
fixed in 0.61
Note that references are not always correctly resolved and might not be renamed.
