### ISSUE TITLE
Jumping to some module-related symbol definitions from Structure Panel doesn't highlight symbol right away

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#91]
plugin version: 0.60.1

### Description

When I click on a symbol in the Structure Panel to jump to its definition, ReasonML normally goes to the appropriate line in the edit window and highlights the symbol (second screen shot),  But if try to jump to the definition of `t`, it jumps to the right line but doesn't highlight the symbol for a couple seconds.  Based on CPU Usage, IJ is working pretty hard in the meantime.

This is what I first see after jumping to `t`.:

![image](https://user-images.githubusercontent.com/1253341/43415891-cabd3d58-9404-11e8-93f8-d5ef7409d079.png)

Compared to jumping to `Branch`, which appears immediately:

![image](https://user-images.githubusercontent.com/1253341/43414952-36afd79e-9402-11e8-8f02-1f5f3360eb44.png)

The 3 highest peaks in CPU Usage correspond to clicking `t`:

![image](https://user-images.githubusercontent.com/1253341/43415680-3d2f75f0-9404-11e8-992a-071d3cf4716a.png)

**Comment by giraud** [comment]
Hi, can you try with version 0.63 ? I'm not sure it's still present in this version

**Comment by jfehrle** [comment]
It seems better.  Jumping to "t" takes maybe 1.25 seconds.  Jumping to "Branch" is faster, maybe .5 seconds.  For both you can see it in two steps: the editor window changing the scroll position and then a moment later highlighting the symbol.

**Comment by giraud** [comment]
fixed in 0.93

**Comment by jfehrle** [comment]
Thanks for the fixes!
