### ISSUE TITLE
Give modules their own color in the Structure panel

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#92]
plugin version: 0.60.2

### Description
Modules and functions have the same pinkish color in the structure panel. It would be much easier to scan for them if modules had their own color,   As it is, I need to take a close look at each entry to find the modules in the list.

![image](https://user-images.githubusercontent.com/1253341/43979324-333ef388-9c9f-11e8-851e-6f3fd3e6c3ce.png)

Also, FWIW, when I see the "f" next to a name in the structure panel, my first thought is "function".  I'd suggest using "f" for bindings that define functions and perhaps "v" (as in "value") for bindings that don't define functions.  Strictly speaking, "λ" refers to anonymous functions (which don't appear in the panel), so that marking is a bit imprecise.  (For Java code, methods (aka functions) are marked with "m" and variables are marked with "f"--perhaps the "f" carried over?)

**Comment by giraud** [comment]
I'm trying to reuse the idea icons, and have no opinion on that subject, but I prefer if I can reuse the existing ones.
you can find one of thems here https://www.jetbrains.com/help/idea/2016.3/symbols.html 
I don't know what would be better

**Comment by jfehrle** [comment]
It would be nice to keep IJ's color coding: things that you can call are pink, data elements are tan, interfaces and annotations are green, classes are blue.  So a pink "f" and a blue "m" (modules seem most similar in concept to classes) seem the best choices--but those are both new icons.  The "v" is already tan.

I didn't see any pre-existing icon that's exactly right.  The icons with lambda and "T" are new, right?

If you'd rather not create new icons, then f and v are not pinkish, so if you switch those, then m for module will stand out better.  And it's mnemonic, at least in English.  (If class methods are eventually listed, they probably should still get an "m" but with the pinkish color used for functions.  Or maybe they should be capital M.)

![image](https://user-images.githubusercontent.com/1253341/44678973-91e7d380-a9ee-11e8-9c3c-8568902e4e39.png)

**Comment by giraud** [comment]
is that better ? 
![image](https://user-images.githubusercontent.com/239612/44706638-940b6a00-aaa2-11e8-8629-34e671ceed6a.png)
I like the lambda for function because it has the correct color by default

**Comment by jfehrle** [comment]
Ah, you used only pre-existing icons.  Not so trivial to create new ones that look right (correct font and anti-aliasing, etc.).  I think the color-coding is probably more important than the letter.  I might try to create some new ones for you but not right away :-(.

**Comment by giraud** [comment]
updated in 0.61.
if it's ok, please close the issue.

**Comment by jfehrle** [comment]
I think the new icon choices are excellent!  I especially like having different colors for function symbols and non-function value symbols.  Very easy to scan the structure panel this way.  Thanks.
