### ISSUE TITLE
Auto-format, the reason I'm using emacs right now

### ISSUE THREAD

**Issue by keynan** [reasonml-editor/reasonml-idea-plugin#93]
plugin version: 0.62

### Description
1) Don't enable auto-format by default (and not just because it's broken).
2) Auto-format of ML files is not disabled by unchecking the setting

**Comment by Coobaha** [comment]
My two cents, plugin print width should be equal to refmt default, which is 80. Current setting is 120. Basically every-time I open new project I need to remember to change it back to 80.

**Comment by giraud** [comment]
hi, 

1. default will stay (120 + auto on)
2. this must be the same than issue #69 , there is collision in settings in some cases but I don't know the root cause yet. still investigating

**Comment by giraud** [comment]
I'm closing this issue because I reworked how compiler and refmt are instanciated in 0.65.
But I'm still not sure it is really fixed.
