### ISSUE TITLE
Class names don't appear in Structure panel

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#95]
plugin version: 0.60.2

### Description

![image](https://user-images.githubusercontent.com/1253341/44631400-c3459e00-a91f-11e8-94c1-47ac16a8543d.png)

**Comment by giraud** [comment]
sorry, class are not yet implemented at the parser level

**Comment by giraud** [comment]
Fixed in 0.63

**Comment by jfehrle** [comment]
Looks good.

It would be great if you could show inherited methods and support navigation to inherited items.  And instance fields (I didn't check those--haven't used OCaml classes too much).

![image](https://user-images.githubusercontent.com/1253341/45841234-051ef580-bcce-11e8-8d8f-f2d4b068436e.png)

Maybe something similar to what IJ does for Java: Clicking the blue dot jumps to the overridden method.  And the tooltip tells you where the item is defined.

![image](https://user-images.githubusercontent.com/1253341/45841531-fb49c200-bcce-11e8-9ddf-861ef5b5bd3d.png)

![image](https://user-images.githubusercontent.com/1253341/45841511-e5d49800-bcce-11e8-831e-87a7dcbf583b.png)

I'll put in a new PR if you like.

**Comment by giraud** [comment]
Yes, please, open 2 different issues, because I don't know yet how to do that
