### ISSUE TITLE
code color not working

### ISSUE THREAD

**Issue by Enalmada** [reasonml-editor/reasonml-idea-plugin#96]
plugin version: 0.60.2

### Description
First I just want to thank you for your effort on this plugin.  It is really critical for new users to reasonml community to have ide support.  I don't seem to have any of the jsx code color that I see in the readme image.  Is there anything I can do to get that working?

![image](https://user-images.githubusercontent.com/1892132/44743380-2d447b80-aab7-11e8-84aa-4dd4cd68023c.png)

**Comment by giraud** [comment]
Hi, thanks.

Go to `Settings|Editor|Color Scheme|Reason` and you'll be able to change the colors of the markups:
![image](https://user-images.githubusercontent.com/239612/44770009-d8603e00-ab66-11e8-8ecf-48e54f784afc.png)

**Comment by Enalmada** [comment]
Oh thanks...that worked!  I feel so silly now not having checked the editor tab. 

Is this plugin in control over the Reason settings?  It could be nice to set some defaults that are consistent with what idea defaults for html.  If not, a note at the bottom of the readme could be helpful to remind new users they are in control over that.

**Comment by giraud** [comment]
I'm not sure I can use default HTML colors. I'm using the default language markup colors that are redefined in HTML language.
