### ISSUE TITLE
Support for rtop / RPEL as tool window

### ISSUE THREAD

**Issue by yunti** [reasonml-editor/reasonml-idea-plugin#97]
There doesn't currently seem to be support for rtop in the IDE (eg as a tool window).  Currently it's just launched from the terminal with no real integration into the IDE.  This is a really useful feature (with eg Haskell has with GHCi or python with ipython/python REPL).

**Comment by giraud** [comment]
Hi, what would be the interaction ?
I think you can already launch a rtop from a terminal window ?

**Comment by yunti** [comment]
Having it integrated as part of the IDE gives a lot better consistency, eg with syntax highlighting, code completion, paired brackets insertion etc..

**Comment by giraud** [comment]
ok, I understand.
something like the cursive repl is interesting: https://cursive-ide.com/userguide/repl.html

**Comment by yunti** [comment]
Yes that's a good example, other things not mentioned there like inline docs, function parameter info etc... are good additions.  I'm not sure how much you would get for free once integrated or how much has to be added manually for each language.  

eg
<img width="242" alt="screen shot 2018-09-21 at 16 09 23" src="https://user-images.githubusercontent.com/1826271/45889681-f9f4c400-bdb8-11e8-8272-ef93c8e91d02.png">
<img width="455" alt="screen shot 2018-09-21 at 16 10 16" src="https://user-images.githubusercontent.com/1826271/45889686-fe20e180-bdb8-11e8-9c67-d3a4b7ebd302.png">
<img width="426" alt="screen shot 2018-09-21 at 16 10 30" src="https://user-images.githubusercontent.com/1826271/45889690-01b46880-bdb9-11e8-99c0-e8df29eafdd8.png">

**Comment by giraud** [comment]
doing some good progress

![image](https://user-images.githubusercontent.com/239612/46696814-62460100-cc13-11e8-9894-390f5632f4e3.png)

![image](https://user-images.githubusercontent.com/239612/46696878-93263600-cc13-11e8-8819-a9c7fbf92854.png)

**Comment by giraud** [comment]
present in 0.65.
