### ISSUE TITLE
Incorrect syntax highlighting when a comment contains "*)" (including the quotes)

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#99]
plugin version: 0.62.1

### Description The 4th line below should have the normal syntax highlighting for code rather than green.

![image](https://user-images.githubusercontent.com/1253341/45646405-0fe04d00-ba78-11e8-8ac8-391010c19101.png)

This shows normal highlighting by adding a space between the `*` and the `)` in the string.

![image](https://user-images.githubusercontent.com/1253341/45646435-27b7d100-ba78-11e8-84dd-e7ac3bd3c2c6.png)

**Comment by giraud** [comment]
Fixed in 0.63

**Comment by jfehrle** [comment]
Looks good, thanks!
